spring:
  config:
    import: env-cloud.yml
  datasource:
    driver-class-name: ${Driver-Class-Name}
    url: ${DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

server:
  error:
    include-message: always
#momo:
#  web-redirect-url: ${DEV_SERVER_DOMAIN}/api/payment/momo/result
#  mobile-redirect-url: mobile
#  ipn-url: ${DEV_SERVER_DOMAIN}/api/payment/momo/result
