USE master;
GO
Drop Database LuvMe;
GO
Create Database LuvMe;
GO
USE LuvMe;


---- Role Table ----
GO
INSERT INTO Role VALUES
('Actor that control and post all the question','ADMIN')
Insert Into Role VALUES
('user use our application','CUSTOMER')

---- User Table ----
GO
INSERT INTO UserTbl (bank_account, birth_day, email, end_premium_date, full_name, gender, is_premium, is_test, start_premium_date, status, role_id)VALUES
(null, null, 'thanhlqse160610@fpt.edu.vn', null, null, null , null, 'false', null, 'NONFULLFILL', 2)

---- Question Table ----
GO
Insert Into Question VALUES(N'Ở vị trí nào bạn thầy rõ dầu và lỗ chân lông trên khuôn mặt ?')
Insert Into Question VALUES(N'Da bạn có bóng loáng lên sau khi rửa mặt trong một khoảng thời gian ngắn ?')
Insert Into Question VALUES(N'Ở vị trí má thường khô ?')
Insert Into Question VALUES(N'Da bạn thính thoáng có bong tróc, xỉn màu hoặc luôn cảm thầy căng da mặt không ?')
Insert Into Question VALUES(N'Da của bạn có thỉnh thoảng kích ứng đỏ hay sưng tấy lên không ?')

---- Result Table ----
GO
Insert Into Result Values(N'Bạn có làn da Dầu',null)
Insert Into Result Values(N'Bạn có làn da Hỗn Hợp',null)
Insert Into Result Values(N'Bạn có làn da Thường',null)
Insert Into Result Values(N'Bạn có làn da Khô',null)
Insert Into Result Values(N'Bạn có làn da Nhạy Cảm',null)

 ---- Answer Table ----
 GO
Insert Into Answer VALUES(N'Toàn Bộ Vị Trí Khuôn Mặt',2,1,null)
Insert Into Answer VALUES(N'Ở vị trí khuôn mặt - cụ thể là trán,mũi,cằm',3,1,null)
Insert Into Answer VALUES(N'Lỗ chân lông rất nhỏ hoặc gần như không thể thấy và có rất ít dầu trên mặt',4,1,null)
Insert Into Answer VALUES(N'Không',3,2,null)
Insert Into Answer VALUES(N'Có',null,2,1)
Insert Into Answer VALUES(N'Có',null,3,2)
Insert Into Answer VALUES(N'Không',null,3,3)
Insert Into Answer VALUES(N'CÓ',null,4,4)
Insert Into Answer VALUES(N'Không',5,4,null)
Insert Into Answer VALUES(N'Không',null,5,4)
Insert Into Answer VALUES(N'Có' ,null,5,5)

---- Suitable Skin Table ----
GO
Insert Into SuitableSkinType VALUES(N'Da hỗn hợp', 'CombinationSkin')
Insert Into SuitableSkinType VALUES(N'Da bình thường', 'NormalSkin')
Insert Into SuitableSkinType VALUES(N'Da dầu', 'OilSkin')
Insert Into SuitableSkinType VALUES(N'Tât cả', 'All')
Insert Into SuitableSkinType VALUES(N'Da Khô', 'DrySkin')
Insert Into SuitableSkinType VALUES(N'Da Nhạy Cảm', 'SensitiveSkin')

---- Category Table ----
GO
Insert Into Category VALUES(N'Sữa rửa mặt',null,null)
Insert Into Category VALUES(N'Tẩy trang',null,null)
Insert Into Category VALUES(N'Đặc trị',null,null)
Insert Into Category VALUES(N'Kem dưỡng ẩm',null,null)
Insert Into Category VALUES(N'Kem lót',null,null)
Insert Into Category VALUES(N'Kem nền',null,null)
Insert Into Category VALUES('Cushion',null,null)
Insert Into Category VALUES(N' Che khuyết điểm',null,null)
Insert Into Category VALUES(N'Phấn phủ',null,null)
Insert Into Category VALUES(N'Xịt khóa makeup',null,null)
Insert Into Category VALUES(N'Tạo khối',null,null)
Insert Into Category VALUES(N'Má hồng',null,null)
Insert Into Category VALUES('Highlight',null,null)
Insert Into Category VALUES(N'Khác',null,null)

---- Characteristic Table ----
GO
Insert Into Characteristic VALUES(N'Sản phẩm không chứa cồn')
Insert Into Characteristic VALUES(N'Sản phẩm không chứa chất hương liệu')
Insert Into Characteristic VALUES(N'Sản phẩm không phải là dạng thuốc')
Insert Into Characteristic VALUES(N'Sản phẩm có thể gây kích thích mụn nám')
Insert Into Characteristic VALUES(N'Sản phẩm không phù hợp cho bà bầu lúc mang thai và cho con bú')
Insert Into Characteristic VALUES(N'Không gây kích ứng')
Insert Into Characteristic VALUES(N'Không chứa paraben')
Insert Into Characteristic VALUES(N'Không gây mụn')
Insert Into Characteristic VALUES(N'Không xà phòng')
Insert Into Characteristic VALUES(N'Không hương liệu')
Insert Into Characteristic VALUES(N'Không chứa paraben')
Insert Into Characteristic VALUES(N'Không bít tắc lỗ chân lông')
Insert Into Characteristic VALUES(N'Đã được kiểm nghiệm không gây kích ứng')
Insert Into Characteristic VALUES(N'Sản phẩm không chứa chất bảo quản')
Insert Into Characteristic VALUES(N'không nhờn rít')
Insert Into Characteristic VALUES(N'Sử dụng vào BAN ĐÊM')
Insert Into Characteristic VALUES(N'Dùng được cho Ban Ngày và Ban Đêm')
Insert Into Characteristic VALUES(N'Hạn chế sử dụng sản phẩm trên các vùng da có vết thương')

---- Ingredient Table ----
GO
Insert Into Ingredient VALUES(N'Thành phần chính, được sử dụng để tạo thành kết cấu của sản phẩm và làm dịu da.',N'Water')
Insert Into Ingredient VALUES(N'Một chất làm ẩm hiệu quả, giúp duy trì độ ẩm cho da, làm cho da mềm mịn.',N'Glycerin')
Insert Into Ingredient VALUES(N'Một chất tạo bọt và làm sạch da, thường được sử dụng trong sản phẩm làm sạch da mặt.',N'Sodium Cocoyl Glycinate')
Insert Into Ingredient VALUES(N'Một chất tạo bọt và làm sạch da, thường được sử dụng trong sản phẩm làm sạch da.',N'Cocamidopropyl Betaine')
Insert Into Ingredient VALUES(N'Có thể là một chất tạo độ nhớt hoặc tạo kết cấu cho sản phẩm.',N'Hydroxypropyl Starch Phosphate')
Insert Into Ingredient VALUES(N'Chất phức tạp kim loại thường được sử dụng để làm cho khoáng chất không tác động đến sản phẩm và giúp điều chỉnh độ pH.',N'Disodium EDTA')
Insert Into Ingredient VALUES(N'Còn gọi là provitamin B5, là một chất làm dịu da và giữ ẩm. Nó có thể giúp làm dịu và cải thiện tình trạng da.',N'Panthenol')
Insert Into Ingredient VALUES(N'Một chất làm dịu da và tạo độ nhớt cho sản phẩm.',N'Hydroxypropyl Methylcellulose')
Insert Into Ingredient VALUES(N'Chất tạo bọt và làm sạch da, thường được sử dụng trong sản phẩm làm sạch da.',N'Disodium Laureth Sulfosuccinate')
Insert Into Ingredient VALUES(N'Một chất tạo bọt và làm sạch da, thường được sử dụng trong sản phẩm làm sạch da.',N'Coco-Betaine')
Insert Into Ingredient VALUES(N'Một dạng của polyethylene glycol, có thể được sử dụng làm chất làm mềm hoặc tạo độ nhớt cho sản phẩm',N'PEG-7 Glyceryl Cocoate')
Insert Into Ingredient VALUES(N'Chất tạo bọt và làm sạch da, thường được sử dụng trong sản phẩm làm sạch da.',N'Sodium Laureth Sulfate')
Insert Into Ingredient VALUES(N'Một chất làm ẩm và tạo độ nhớt cho sản phẩm.',N'Hexylene Glycol')
Insert Into Ingredient VALUES(N'Một dạng của polyethylene glycol, có thể được sử dụng làm chất làm mềm hoặc tạo độ nhớt cho sản phẩm.',N'PEG-6 Caprylic/Capric Glycerides')
Insert Into Ingredient VALUES(N'Một chất tạo độ nhớt và làm mềm da, thường được sử dụng trong sản phẩm chăm sóc tóc.',N'Cetrimonium Chloride')
Insert Into Ingredient VALUES(N'Chất làm dịu da và làm mềm da, có thể giúp duy trì độ ẩm cho da',N'Fructooligosaccharides')
Insert Into Ingredient VALUES(N'Một loại đường tự nhiên, có thể được sử dụng để cung cấp độ ẩm cho da',N'Mannitol')
Insert Into Ingredient VALUES(N'Một loại đường tự nhiên, có thể giúp duy trì độ ẩm cho da và có tính chất làm dịu.',N'Xylitol')
Insert Into Ingredient VALUES(N'Một loại đường tự nhiên, có thể giúp làm mềm da và giữ ẩm.',N'Rhamnose')
Insert Into Ingredient VALUES(N'Một loại tinh bột có thể được sử dụng để tạo độ nhớt hoặc kết cấu cho sản phẩm.',N'Dextrin')
Insert Into Ingredient VALUES(N'Có thể là một loại dextrin đã được xử lý để có khả năng làm mềm da hoặc tạo kết cấu cho sản phẩm.',N'Dextrin Palmitate/Ethylhexanoate')
Insert Into Ingredient VALUES(N'Dạng tinh chất của acid hyaluronic, được sử dụng để cung cấp độ ẩm cho da và làm dịu da.',N'Sodium Acetylated Hyaluronate')
Insert Into Ingredient VALUES(N'Dầu chiết xuất từ quả ô liu, có khả năng cung cấp dưỡng chất cho da, làm dịu và giữ ẩm cho da.',N'Olea Europaea')
Insert Into Ingredient VALUES(N'Một loại dầu có nguồn gốc từ dầu dừa và axit béo caprylic/capric. Thường được sử dụng làm chất làm mềm da và tạo độ nhớt cho sản phẩm.',N'Caprylic/Capric Triglycerides')
Insert Into Ingredient VALUES(N'Một chất tạo độ nhớt và làm mềm da.',N'Sorbeth-30 Tetraoleate')
Insert Into Ingredient VALUES(N'Một dạng của acid glycyrrhetinic, có khả năng làm dịu da và có tính chất chống viêm.',N'Stearyl Glycyrrhetinate')
Insert Into Ingredient VALUES(N'Dầu chiết xuất từ lá hương thảo, thường được sử dụng để tạo mùi thơm cho sản phẩm và có tính chất làm dịu da.',N'Leaf Oil')
Insert Into Ingredient VALUES(N'Một loại hydrocarbon, thường được sử dụng làm chất làm mềm cho da và tạo độ nhớt cho sản phẩm.',N'C15-19 Alkane')
Insert Into Ingredient VALUES(N'Một dạng của glycerin, có khả năng làm dịu da và giữ ẩm cho da.',N'Glycereth-26')
Insert Into Ingredient VALUES(N'Một chất tạo bọt và làm sạch da, thường được sử dụng trong sản phẩm làm sạch da.',N'Polysorbate 20')
Insert Into Ingredient VALUES(N'Dầu chiết xuất từ hoa hồng Damascena, thường được sử dụng để tạo mùi thơm cho sản phẩm và có tính chất làm dịu da.',N'Rosa Damascena Flower Oil')
Insert Into Ingredient VALUES(N'Một dạng của acid béo, thường được sử dụng làm chất làm mềm cho da hoặc tạo độ nhớt cho sản phẩm',N'Ethylhexyl Palmitate')
Insert Into Ingredient VALUES(N'Dầu chiết xuất từ hạt cây cải thiện da, có khả năng cung cấp dưỡng chất cho da và giữ ẩm.',N'Organic Carthamus Tinctorius')
Insert Into Ingredient VALUES(N'Một dạng của axit béo caprylic, thường được sử dụng làm chất làm mềm cho da hoặc tạo độ nhớt cho sản phẩm.',N'Caprylic')
Insert Into Ingredient VALUES(N'Một chất làm mềm da và tạo độ nhớt cho sản phẩm, thường được sử dụng trong sản phẩm chăm sóc da.',N'Polyethylene')
Insert Into Ingredient VALUES(N'Một dạng của polyethylene glycol, có thể được sử dụng làm chất làm mềm hoặc tạo độ nhớt cho sản phẩm.','PEG-5 Glyceryl Triisostearat')
Insert Into Ingredient VALUES(N'Một dạng của dầu, có khả năng làm mềm da và tạo độ nhớt cho sản phẩm.','Cetyl Ethylhexanoate')
Insert Into Ingredient VALUES(N'Một dạng của polyethylene glycol, có thể được sử dụng làm chất làm mềm hoặc tạo độ nhớt cho sản phẩm.','PEG-20 Glyceryl Triisostearate')
Insert Into Ingredient VALUES(N'Một loại polyethylene glycol, có khả năng làm mềm da và tạo độ nhớt cho sản phẩm.','PEG-10 Isostearate')
Insert Into Ingredient VALUES(N' Một loại sáp tổng hợp, thường được sử dụng để tạo độ nhớt và kết cấu cho sản phẩm','Synthetic Wax')
Insert Into Ingredient VALUES(N'Có thể là nước khoáng từ suối nhiệt đới (onsen) ở Nhật Bản. Thường được sử dụng để cung cấp khoáng chất cho da.','Onsen-Sui')
Insert Into Ingredient VALUES(N'Một chất bảo quản, thường được sử dụng để gia tăng tuổi thọ của sản phẩm và ngăn sự phát triển của vi khuẩn và mốc.','Phenoxyethanol')
Insert Into Ingredient VALUES(N'Một chất làm ẩm và tạo độ nhớt cho sản phẩm, giúp duy trì độ ẩm cho da.','Butylene Glycol')
Insert Into Ingredient VALUES(N'Chiết xuất từ cây rễ Lithospermum Erythrorhizon, thường được sử dụng để làm dịu và bảo vệ da.','Lithospermum Erythrorhizon Root Extract')
Insert Into Ingredient VALUES(N'Nước đã được loại bỏ các ion và các chất cản trở, được sử dụng làm dung môi chính trong sản phẩm.','Deionized Water')
Insert Into Ingredient VALUES(N'Ascorbic Acid là một dạng của axit béo tự nhiên, có khả năng kiểm soát sự sản xuất của melanin, giúp làm sáng da và làm giảm nám da và tình trạng mụn.','Azelaic Acid')
Insert Into Ingredient VALUES(N'Tocopherol là một dạng của Vitamin E, có khả năng chống oxi hóa, bảo vệ làn da khỏi tổn thương do tác động của tia UV và gốc tự do.','Tocopherol')
Insert Into Ingredient VALUES(N' Collagen là một loại protein quan trọng trong da và các mô liên quan. Sản phẩm này có thể chứa collagen để cung cấp độ đàn hồi và độ đàn hồi cho da.','Collagen')
Insert Into Ingredient VALUES(N'Ubiquinone, còn được gọi là Coenzyme Q10, là một chất chống oxi hóa tự nhiên trong da. Nó có thể giúp cung cấp năng lượng cho tế bào da và giúp làm giảm nếp nhăn.','Ubiquinone')
Insert Into Ingredient VALUES(N'Carbomer là một loại polymer có khả năng tạo độ nhớt và độ đặc cho sản phẩm, giúp làm dịu và dễ dàng sử dụng.','Carbomer')
Insert Into Ingredient VALUES(N'Acrylates Copolymer là một polymer được sử dụng trong sản phẩm để tạo độ đặc và làm cho sản phẩm có khả năng bám dính vào da',N'Acrylates Copolymer')
Insert Into Ingredient VALUES(N'Alcohol là một chất có khả năng làm khô nhanh và làm mát da. Tuy nhiên, nếu sử dụng quá nhiều, nó có thể gây khô da',N'Alcohol')
Insert Into Ingredient VALUES(N'VP (Vinyl Pyrrolidone) thường được sử dụng trong sản phẩm làm đẹp để cải thiện tính nhớt và độ bám dính của sản phẩm',N'Vp')
Insert Into Ingredient VALUES(N'Salicylic Acid là một loại acid beta hydroxy (BHA) thường được sử dụng trong sản phẩm chăm sóc da để loại bỏ tế bào da chết và giúp làm sáng và làm mịn da',N'Salicylic Acid')
Insert Into Ingredient VALUES(N'Adapalene là một dạng thuốc chống mụn, thường được sử dụng để điều trị mụn trứng cá và mụn đầu đen',N'Adapalene')
Insert Into Ingredient VALUES(N'Carbomer 934P là một loại polymer thường được sử dụng trong sản phẩm làm đẹp để làm đặc và tạo độ nhớt.',N'Carbomer 934P')
Insert Into Ingredient VALUES(N'Cyclomethicone là một loại silicone thường được sử dụng để làm mịn và cải thiện cảm giác của sản phẩm trên da.',N'Cyclomethicone')
Insert Into Ingredient VALUES(N'Disodium EDTA là chất chelating, thường được sử dụng để giữ các ion kim loại trong sản phẩm và tăng độ ổn định.',N'Disodium EDTA')
Insert Into Ingredient VALUES(N'Tretinoin là một dạng của axit retinoic, thường được sử dụng trong sản phẩm chăm sóc da để làm giảm nếp nhăn và điều trị mụn.',N'Tretinoin')
Insert Into Ingredient VALUES(N'Polyethylene glycol stearate là một dạng của polyethylene glycol kết hợp với axit stearic. Thường được sử dụng để làm mềm và làm dịu da.',N'Polyethylene glycol stearate')
Insert Into Ingredient VALUES(N'Glycerol stearate và PEG-100 stearate thường được sử dụng trong sản phẩm làm đẹp làm tăng độ nhớt và giữ ẩm cho da.',N'Glycerol Stearate and PEG-100 Stearate')
Insert Into Ingredient VALUES(N'Cetyl alcohol là một loại dẫn xuất của dầu có khả năng làm mềm và dưỡng ẩm cho da.',N'Cetyl Alcohol')
Insert Into Ingredient VALUES(N'Stearyl alcohol cũng là một loại dẫn xuất của dầu, thường được sử dụng để làm dịu và làm mềm da.',N'Stearyl Alcohol')
Insert Into Ingredient VALUES(N'Nước, là thành phần chính của sản phẩm, được sử dụng làm dung môi.',N'Aqua / Water')
Insert Into Ingredient VALUES(N'Aminomethyl propanol là một chất điều chỉnh độ pH thường được sử dụng để điều chỉnh độ axit trong sản phẩm.',N'Aminomethyl Propanol')
Insert Into Ingredient VALUES(N'Glycolic acid là một loại axit alpha hydroxy (AHA) thường được sử dụng để tẩy tế bào chết và cải thiện kết cấu da.',N'Glycolic Acid')
Insert Into Ingredient VALUES(N'Lactic acid là một loại AHA thường được sử dụng để làm dịu và làm mềm da.',N'Lactic Acid')
Insert Into Ingredient VALUES(N'Mandelic acid là một loại AHA có kích thước phân tử lớn hơn, thường được sử dụng để cải thiện sự đồng đều của làn da.',N'Mandelic Acid')
Insert Into Ingredient VALUES(N'Palmitoyl oligopeptide là một loại peptide thường được sử dụng để cải thiện độ đàn hồi và độ săn chắc của da.',N'Palmitoyl Oligopeptide')
Insert Into Ingredient VALUES(N'Palmitoyl tetrapeptide-7 là một loại peptide thường được sử dụng để làm dịu da và cải thiện tình trạng viêm nhiễm.',N'Palmitoyl Tetrapeptide-7')
Insert Into Ingredient VALUES(N'Saccharomyces lysate là một dạng của men, có thể cung cấp dưỡng chất cho da và giúp làm dịu.',N'Saccharomyces Lysate')
Insert Into Ingredient VALUES(N'Chiết xuất từ hoa Arnica Montana, có khả năng làm dịu da và giảm sưng.',N'Arnica Montana Flower Extract')
Insert Into Ingredient VALUES(N'Hiệu quả cấp ẩm, làm mềm và bảo vệ da trong thời gian dài Vitamin PP giúp kích thích lớp lipids tổng hợp, tái tạo rào chắn tự nhiên, từ đó cải thiện độ mềm mịn và khôi phục cảm giác dịu nhẹ trên da một cách lâu dài.',N'Glycerine và Vaseline')
Insert Into Ingredient VALUES(N'Mang lại hiệu quả kháng khuẩn, kháng viêm cho mụn, giúp mờ thâm do mụn gây ra, làm dịu da và tái tạo da.',N'Madecassoside')
Insert Into Ingredient VALUES(N'Cải thiện sự cân bằng lượng dầu – nước, tổng hợp collagen ở tầng biểu bì giúp da căng mịn, mềm da và cấp ẩm cho da luôn mềm mại.',N'Asiaticoside')
Insert Into Ingredient VALUES(N'Giúp củng cố sức mạnh cho làn da, tăng cường khả năng tự bảo vệ của da, làm dịu làn da mẫn cảm, chống oxy hóa, cải thiện độ đàn hồi của da.',N'Asiatic Axit')
Insert Into Ingredient VALUES(N'Làm dịu làn da mệt mỏi, cải thiện những vết tích trên da, làm lành làn da bị tổn thương, phục hồi, cân bằng độ ẩm và tái sinh tế bào da non.',N'Madecassic Axid')
Insert Into Ingredient VALUES(N'Phức hợp độc quyền giúp cân bằng hệ vi sinh vật trên da, tăng cường hoạt động của lợi khuẩn & ức chế sự phát triển của hại khuẩn.',N'Tribimoia')
Insert Into Ingredient VALUES(N'Tăng cường khả năng tái tạo tế bào trên da, giúp phục hồi nhanh hơn.',N'5% Vitamin B5 (Panthenol)')
Insert Into Ingredient VALUES(N'Dưỡng ẩm và củng cố hàng rào bảo vệ da.',N'Bơ Hạt Mỡ')
Insert Into Ingredient VALUES(N'Là thành phần tạo nên màu xanh tự nhiên cho sản phẩm, có đặc tính chữa lành tổn thương trên da, giúp làm dịu da và kích thích tái tạo các tế bào da. Ngoài ra Guaiazulene còn kháng khuẩn, kháng viêm, chống oxy hóa, hỗ trợ ngăn ngừa mụn và ngăn ngừa các dấu hiệu lão hóa da.',N'Guaiazulene (chiết xuất từ dầu hoa cúc)')
Insert Into Ingredient VALUES(N'Dưỡng ẩm cho da mềm mượt.',N'Hyaluronic Acid')
Insert Into Ingredient VALUES(N'Hỗ trợ phục hồi hàng rào bảo vệ da khỏe mạnh hơn.',N'Ceramide 3')
Insert Into Ingredient VALUES(N'Giàu axit béo dưỡng ẩm cho da, ngăn ngừa các dấu hiệu lão hóa.',N'Dầu Argan')
Insert Into Ingredient VALUES(N'Điều tiết lượng dầu, nhờn cho da.',N'Cetyl Ethylhexanoate')
Insert Into Ingredient VALUES(N'Thay đổi tế bào da hiệu quả giúp da căng mịn và mềm mại, kích thích sản xuất collagen, cải thiện độ đàn hồi, săn chắc của làn da, làm sạch lỗ chân lông, kiềm dầu và giảm mụn hiệu quả.',N'Retinal 1%')
Insert Into Ingredient VALUES(N'Làm giảm mụn cám, mụn bọc và mụn đầu đen, tẩy tế bào chết, làm sạch sâu, thu nhỏ lỗ chân lông, giảm vết thâm nám, nếp nhăn, ngăn ngừa lão hóa, cải thiện cấu trúc da và kiểm soát lượng dầu thừa da.',N'BHA')
Insert Into Ingredient VALUES(N'Có khả năng làm mờ các vết thâm, làm đều màu da và cải thiện nâng tông da.',N'Niacinamide 4%')
Insert Into Ingredient VALUES(N'Tẩy tế bào chết, làm thông thoáng lỗ chân lông, ngăn ngừa mụn mới hình thành thành và cải thiện sẹo mụn và vết thâm do mụn để lại.',N'AHA')
Insert Into Ingredient VALUES(N'Làm sáng da, ức chế sự hình thành phần sắc tố melanin, ngăn chặn hình thành các đốm nâu và lão hóa',N'Illumiscin')
Insert Into Ingredient VALUES(N'Thành phần Vitamin C bền vững tăng cường collagen giúp Giúp Tái Tạo Da làn da',N'STAY-C® 50')
Insert Into Ingredient VALUES(N'Cũng là một dạng của silicone, có khả năng tạo màng bảo vệ trên da và cải thiện độ bám của mỹ phẩm trên da.',N'Dimethicone Crosspolymer')
Insert Into Ingredient VALUES(N'Là một dạng của este, thường được sử dụng để cung cấp độ mềm mại cho sản phẩm và làm cho sản phẩm dễ lan truyền trên da.',N'Stearyl Heptanoate')
Insert Into Ingredient VALUES(N'Là một chất chống nấm mốc và vi khuẩn, thường được sử dụng để tăng tuổi thọ và bảo quản sản phẩm mỹ phẩm.',N'Caprylyl Glycol')
Insert Into Ingredient VALUES(N' Là một dạng của khoáng chất silica, được sử dụng để tạo cảm giác mịn màng và giúp kiểm soát dầu trên da.',N'Silica Silylate')
Insert Into Ingredient VALUES(N'Là một dạng của este, thường được sử dụng để cung cấp độ mềm mại cho sản phẩm và giúp sản phẩm dễ lan truyền trên da',N'Isopropyl Palmitate')
Insert Into Ingredient VALUES(N' Là một khoáng chất thường được sử dụng trong mỹ phẩm để tạo màu sắc trắng hoặc làm chất chống nắng vật lý',N'Titanium Dioxide')
Insert Into Ingredient VALUES(N'Đây là các dạng của silicone, thường được sử dụng để làm mịn da và tạo lớp màng bảo vệ trên da.',N'Cyclopentadimethylsiloxane và Polydimethylsiloxane')
Insert Into Ingredient VALUES(N'Titanium dioxide là một khoáng chất thường được sử dụng trong mỹ phẩm để tạo màu sắc trắng hoặc làm chất chống nắng vật lý',N'CC7891/TITANIUM DIOXIDE')
Insert Into Ingredient VALUES(N'Là một dạng của silicone, thường được sử dụng để tạo cảm giác mịn màng trên da.',N'CYCLOHEXASILOXANE')
Insert Into Ingredient VALUES(N'Là một loại chất chống nắng hóa học, thường được sử dụng để bảo vệ da khỏi tác động của tia UVB',N'Ethylhexyl Methoxycinnamate')
Insert Into Ingredient VALUES(N'Là một chất chống nắng hóa học khác, thường được sử dụng để bảo vệ da khỏi tác động của tia UVA.',N'Ethylhexyl Salicylate')
Insert Into Ingredient VALUES(N'Titanium dioxide là một khoáng chất thường được sử dụng trong mỹ phẩm để tạo màu sắc trắng hoặc làm chất chống nắng vật lý.',N'Titanium Dioxide')
Insert Into Ingredient VALUES(N'Là một dạng của silicone, thường được sử dụng để làm mịn da và tạo lớp màng bảo vệ trên da.',N'Diphenylsiloxy Phenyl Trimethicone')
Insert Into Ingredient VALUES(N'Đây là các chất chống nắng hóa học, thường được sử dụng để bảo vệ da khỏi tác động của tia UVB.',N'Homosalate, Ethylhexyl Salicylate, Phenyl Trimethicone')
Insert Into Ingredient VALUES(N'Các chất phụ gia thường được sử dụng để cung cấp độ dẻo, ẩm, và độ bám cho sản phẩm.',N'Trimethylsiloxysilicate, Butylene Glycol, Glycerin, Propylene Glycol Dibenzoate')
Insert Into Ingredient VALUES(N'Là các dạng của silicone, thường được sử dụng để cung cấp độ bám và tạo lớp màng bảo vệ trên da.',N'Lauryl PEG-10 Tris(Trimethylsiloxy)silylethyl Dimethicone, Acrylates/Dimethicone Copolymer')
Insert Into Ingredient VALUES(N'Là một dạng của vitamin B3, thường được sử dụng để cung cấp dưỡng chất và làm sáng da.',N'Niacinamide')
Insert Into Ingredient VALUES(N' Đây là các dạng của silicone, thường được sử dụng để làm mịn da và tạo lớp màng bảo vệ trên da.',N'Cyclopentasiloxane và Cyclohexasiloxane')
Insert Into Ingredient VALUES(N'Là một dạng của hydrocarbon, thường được sử dụng để làm cho sản phẩm dễ tán và tạo cảm giác nhẹ trên da.',N'Isododecane')
Insert Into Ingredient VALUES(N'Là một chất làm ẩm tự nhiên, thường được sử dụng để giữ nước cho da.',N'Glycerin')
Insert Into Ingredient VALUES(N'Là một dạng của silicone, có khả năng làm mềm da và cung cấp độ bám cho sản phẩm.',N'Peg-9 Polydimethylsiloxyethyl Dimethicone')
Insert Into Ingredient VALUES(N'Titanium dioxide, một khoáng chất thường được sử dụng trong mỹ phẩm để tạo màu trắng hoặc làm chất chống nắng vật lý.',N'Ci 77891')
Insert Into Ingredient VALUES(N'Một dạng của silicone, thường được sử dụng để làm mềm da và cung cấp độ bám cho sản phẩm.',N'Cyclopentasiloxane')
Insert Into Ingredient VALUES(N'Đây là các dạng của silicone, thường được sử dụng để cung cấp độ mềm mại và tạo lớp màng bảo vệ trên da.',N'Trimethylsiloxyphenyl Dimethicone và Trimethylsiloxysilicate')
Insert Into Ingredient VALUES(N'Sắt oxides, các mã màu sử dụng trong mỹ phẩm để tạo màu sắc.',N'Ci 77492 và Ci 77491')
Insert Into Ingredient VALUES(N'Một loại chất phụ gia thường được sử dụng để cung cấp độ bám và tạo hiệu ứng bóng cho sản phẩm trang điểm.',N'Magnesium Potassium Fluorosilicate')
Insert Into Ingredient VALUES(N'Silica thường được sử dụng để kiểm soát dầu và làm mờ lỗ chân lông.',N'Silica')
Insert Into Ingredient VALUES(N'Là một loại chất phụ gia thường được sử dụng để cung cấp độ mềm mại cho sản phẩm trang điểm.',N'Octyldodecyl Stearoyl Stearate')
Insert Into Ingredient VALUES(N'Là một dạng của silicone, thường được sử dụng để cung cấp độ bám và tạo lớp màng bảo vệ trên da.',N'Silica Dimethicone Silylate')
Insert Into Ingredient VALUES(N'Talc là một khoáng chất thường được sử dụng trong mỹ phẩm, đặc biệt là trong phấn mắt và phấn phủ. Nó giúp làm mịn da và kiểm soát dầu.',N'Talc')
Insert Into Ingredient VALUES(N'Perlite là một khoáng chất thường được sử dụng để kiểm soát dầu và làm mờ lỗ chân lông.',N'Perlite')
Insert Into Ingredient VALUES(N'Là một loại chất làm mềm da và chất bảo vệ da.',N'Triisostearin')
Insert Into Ingredient VALUES(N'Là một dạng của silicone, thường được sử dụng để làm mềm da và tạo lớp màng bảo vệ trên da.',N'Phenyl Trimethicone')
Insert Into Ingredient VALUES(N'Magnesium stearate là một muối của axit stearic, thường được sử dụng để cung cấp độ nhớt cho sản phẩm và cải thiện độ bám.',N'Magnesium Stearate')
Insert Into Ingredient VALUES(N'Ethanol, còn được gọi là cồn, thường được sử dụng trong mỹ phẩm làm chất tạo độ sạch và chất bảo quản.',N'ETHANOL')
Insert Into Ingredient VALUES(N' Là một loại dung môi và chất làm ẩm, thường được sử dụng để cung cấp độ ẩm cho da.',N'BUTANEDIOL')
Insert Into Ingredient VALUES(N'Là một loại polymer thường được sử dụng trong sản phẩm chăm sóc tóc để cung cấp độ bám và kiểm soát tóc',N'VP/VA COPOLYMER')
Insert Into Ingredient VALUES(N'Alcohol Denat. là cồn đã được tinh chế để loại bỏ nước và các chất phụ gia khác.','Alcohol Denat')
Insert Into Ingredient VALUES(N'PVP là một polymer thường được sử dụng trong mỹ phẩm để cung cấp độ bám và độ cứng cho sản phẩm.','PVP (Polyvinylpyrrolidone)')
Insert Into Ingredient VALUES(N'Là một dạng của polymer, thường được sử dụng để cung cấp độ bám và làm cho sản phẩm dễ tán..','AMP-Acrylates/Allyl Methacrylate Copolymer')
Insert Into Ingredient VALUES(N'Là một loại chất làm ẩm và dung môi, thường được sử dụng để giữ cho sản phẩm mỹ phẩm không bị khô.','Butylene Glycol')
Insert Into Ingredient VALUES(N'Là một loại chất phụ gia thường được sử dụng để cung cấp độ bám và độ nhớt cho sản phẩm.','Pentaerythrityl Tetraethylhexanoate')
Insert Into Ingredient VALUES(N'Là một loại chất phụ gia thường được sử dụng để kiểm soát dầu và làm mờ lỗ chân lông.','Nylon-12')
Insert Into Ingredient VALUES(N'Là một loại dầu, thường được sử dụng trong sản phẩm son môi để cung cấp độ mềm mại và làm dịu môi.','Isononyl Isononanoate')
Insert Into Ingredient VALUES(N' Đây là các dạng của silicone, thường được sử dụng để làm mềm môi, cung cấp độ bóng và tạo lớp màng bảo vệ.','Phenyl Trimethicone')
Insert Into Ingredient VALUES(N'Polyethylene thường được sử dụng để làm cho sản phẩm son môi có độ cứng và độ bám.','Polyethylene')
Insert Into Ingredient VALUES(N'Microcrystalline wax thường được sử dụng để tạo độ bóng và độ cứng cho sản phẩm son môi.','Microcrystalline Wax')
Insert Into Ingredient VALUES(N'Ozokerite là một loại wax khoáng, thường được sử dụng trong sản phẩm son môi để cung cấp độ bám và độ cứng','Hydrogenated Polyisobutene')
Insert Into Ingredient VALUES(N'Mica thường được sử dụng để tạo sự bóng và ánh sáng cho sản phẩm trang điểm.','Mica (CI 77019)')
Insert Into Ingredient VALUES(N'Là một loại chất làm mềm môi và chất bảo vệ môi.','Hydrogenated Poly(C6-14 Olefin)')
Insert Into Ingredient VALUES(N'Là một loại dầu, thường được sử dụng để làm mềm môi và cung cấp độ bóng.','Octyldodecanol')
Insert Into Ingredient VALUES(N'Là một loại polymer thường được sử dụng để cung cấp độ bám và độ cứng cho sản phẩm son môi.','Hydrogenated Styrene/Isoprene Copolymer')
Insert Into Ingredient VALUES(N'Đây là các loại chất làm mềm da và chất bảo vệ da.','Triisostearin, Phenyl Trimethicone')
Insert Into Ingredient VALUES(N'Là một loại chất phụ gia thường được sử dụng để tạo sự bóng và ánh sáng trong mỹ phẩm.','Synthetic Fluorphlogopite')
Insert Into Ingredient VALUES(N'Là một chất bảo quản và chất làm dịu da thường được sử dụng trong mỹ phẩm.','Caprylyl Glycol')
Insert Into Ingredient VALUES(N'Đây là các chất phụ gia thường được sử dụng để tạo độ bóng và ánh sáng trong mỹ phẩm.','Alumina, Silica, Magnesium Silicate')
Insert Into Ingredient VALUES(N'Đây là một loại polymer có khả năng làm cho sản phẩm trông mịn và dễ lấy.','METHYL METHACRYLATE CROSSPOLYMER')
Insert Into Ingredient VALUES(N'Một loại dầu gốc thực vật thường được sử dụng để làm dịu và làm mềm da.','DIISOSTEARYL MALATE')
Insert Into Ingredient VALUES(N'Một loại chất tổng hợp thường được sử dụng để tạo ra ánh kim loại trong mỹ phẩm.','SYNTHETIC FLUORPHLOGOPITE')
Insert Into Ingredient VALUES(N'Đây là một loại silicone thường được sử dụng để cung cấp sự mịn màng và sự trơn tru trên da.','DIMETHICONE')
Insert Into Ingredient VALUES(N'Đây là các hợp chất silicone khác thường được sử dụng để tạo cảm giác mềm mịn và dễ lấy của sản phẩm trên da.','CYCLOPENTASILOXANE và CYCLOHEXASILOXANE')
Insert Into Ingredient VALUES(N'Đây là các polymer silicone thường được sử dụng để cải thiện độ bám và lâu trôi của sản phẩm trên da.','DIMETHICONE CROSSPOLYMER và DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER')
Insert Into Ingredient VALUES(N'Một chất emulsifying thường được sử dụng để kết hợp các thành phần dầu và nước trong sản phẩm.','POLYGLYCERYL-2 TRIISOSTEARATE')

---- Product Table ----
GO
Insert Into Product VALUES('bd7653af-238d-4762-bb89-77bf94c5941e',N'Hada Labo ADVANCED NOURISH Hyaluron Cleanser là sữa rửa mặt dưỡng ẩm đến từ Hada Labo. Sản phẩm không cồn khô, hương liệu tuy nhiên chứa chiết xuất Cananga Odorata Flower Oil có thể gây kích ứng một số làn da nhạy cảm. Thành phần còn có các chất làm nền da và giữa ẩm như HA, SHA và Nano HA nên rất dịu và gữ ẩm cho làn da tốt. Khả năng làm sạch tốt, tao bọt dịu nhẹ không làm mất đi độ ẩm làn da. Công nghệ hiện đại làm sạch bằng các gốc anmino acid nên nhẹ dịu cho làn da hơn. Giá rất rẻ, làm sạch nhẹ nhàng, tìm mua được ở mọi nơi.', null, 'Hada Labo ADVANCE NOURISH Hyaluron Cleanser')
Insert Into Product VALUES('aaebaede-6390-42f3-995b-1873ae0bddcc',N'Sửa rửa mặt dịu nhẹ cho da nhạy cảm của thương hiệu Simple. Sản phẩm không chứa cồn khô, hương liệu nên khá an toàn cho da nhạy cảm nè! Kết cấu sản phẩm là loại gel mỏng, khi rửa với nước hầu như không tạo bọt, giúp rửa mặt nhưng vẫn không gây khô da. Tuy nhiên, nếu bạn nào hay makeup hoặc hay làm việc ngoài trời thì có thể sẽ cần sản phẩm làm sạch tốt hơn',null,'Simple Refreshing Facial Gel Wash')
Insert Into Product VALUES('1ea9bfe9-8736-44dc-afbb-e463cab9fc5c',N'Sebiaclear gel moussant là SRM không chứa SOAP (xà phòng), giúp làm sạch và loại bỏ bã nhờn mà không làm da quá khô.Nhìn chung thì sản phẩm này tập trung vào làm sạch nhờn và bụi bẩn trên bề mặt da do chứa các chất hoạt động bề mặt như Disodium Laureth Sulfosuccinate, PEG-7 Glyceryl Cocoate,... bên cạnh đó do có chứa Lactic acid(AHA) và Gluconolactone (PHA) giúp tẩy tế bào chết nhẹ nhàng và làm thông thoáng lỗ chân lông. Do có chứa acid nên chỉ hợp với da dầu.',null,'SVR Sebiaclear Gel Moussant')
Insert Into Product VALUES('f95dcf90-4c49-44bf-aacd-ff98adbae1cf',N'Sản phẩm tẩy trang tốt từ nhà Simple - một nhãn hiệu mỹ phẩm lành tính phân khúc trung bình tại Anh. Sản phẩm có một số đặc điểm như sau: Không cồn, không hương liệu,Tẩy trang khá ổn với các sản phẩm chống nắng và makeup thông thường, tuy nhiên đối với mascara chống nước thì sẽ hơi khó tẩy trang tí.Có bổ sung một số thành phần dưỡng như Glycerin, Niacinamide và Panthenol (VitB5) giúp làm sạch da nhưng vẫn dưỡng ẩm cho da.Nhìn chung là thành phần an toàn, ngoại trừ Cetrimonium Chloride - có thể gây dị ứng với da quá nhạy cảm (tuy vậy cũng khá hiếm và nồng độ thành phần này cũng được kiểm soát trong sản xuất',null,'Simple Kind to Skin Micellar Cleansing Water')
Insert Into Product VALUES('91918e2b-5832-46b8-9842-9841197bca79',N'Sản phầm nước tẩy trang không chứa các chất dễ kích ứng như ethanol, hương liệu; bảng thành phần nhìn chung lành tính, phù hợp với da nhạy cảm và có thể sử dụng cho cả các mẹ bầu.Cách sử dụng: Đổ lượng vừa đủ sản phẩm ra bông tẩy trang và lau đi lớp makeup/ kem chống nắng. Có thể không cần rửa lại với nước',null,'LOreal Paris Micellar Water 3 In 1 Refreshing')
Insert Into Product VALUES('23b71d2a-dbe5-4c16-916c-bb63dfd2d383',N'Sản phẩm tẩy trang nổi tiếng của Bioderma dành cho da nhạy cảm. Sản phẩm chứa một số đặc điểm như:Khả năng tẩy trang tốt với công nghệ micelle: Các phân tử Micelle có một đầu hòa tan được với nước và đuôi gốc dầu, và theo trang web của Bioderma thì với cấu trúc này, các phân tử này có thể hút tất cả các loại tạp chất và sau đó giữ các tạp chất này trên miếng bông tẩy trang. Điều này có nghĩa là nó có thể loại bỏ tất cả các chất cặn bả từ môi trường bên ngoài (ví dụ như lớp makeup, hay tạp chất từ ô nhiễm không khí...) và cả các bã nhờn có sẵn trên da (là thành phần Peg-6 Caprylic/Capric Glycerides)',null,'Bioderma Sensibio H20')
Insert Into Product VALUES('7e5e1b0d-93f1-4d20-91b9-2f2a9d036249',N'Dầu tẩy trang nổi tiếng của thương hiệu Hada Labo: dịu nhẹ, ít gây kích ứng, giá thành vừa phải, phù hợp với phần lớn người tiêu dùng.Dầu tẩy trang này có gốc dầu nền là dầu Olive.Bảng thành phần khá lành tính, tuy nhiên không thích hợp với các bạn bị mụn nấm.',null,'Hada Labo Advanced Nourish Hyaluron Cleansing Oil')
Insert Into Product VALUES('816bf9e3-2730-49a6-99cc-889c047e42a3',N'Làm sạch sâu lớp trang điểm, bụi bẩn và bã nhờn, Cung cấp độ ẩm, mang đến làn da sạch, mềm mịn mà không để lại cảm giác nhờn rít trên da. Thành phần chính có: Dầu hoa hồng giúp ngăn ngừa lão hóa, cấp ẩm sâu cho làn da, Vitamin E giúp dưỡng ẩm, làm mềm da và chống oxy hóa cho làn da.Vì là hệ vi nhũ hoá 2 pha liên tục nên có thể sử dụng trên da ướt và da khô mà vẫn cho hiệu quả làm sạch sâu, không giống những dầu tẩy trang thông thường phải sử dụng trên da khô mới phát huy tối đa hiệu quả làm sạch.',null,N'Dầu tẩy trang hoa hồng cocoon')
Insert Into Product VALUES('f9958782-9b00-4b5d-a8b6-c6961d2ae039',N'Đây là sáp tẩy trang đến từ nhà Clinique, đây là một trong những nhãn hàng phân khúc cao cấp trong làng skincare. Vì vậy chúng ta không cần phải nói quá nhiều về nhãn hàng này nữa.Thành phần giúp tẩy trang tốt cho sản phẩm đó là các loại Seed Oil, Capric Triglyceride, giúp loại bỏ đi được toàn bộ lớp make up một cách dễ dàng.Chuyển đổi từ một loại dầu dưỡng rắn thành một loại dầu mượt mà khi sử dụng. Khả năng làm sạch tốt và kỹ, có thể nhũ hóa với nước giúp rửa sạch hoàn toàn. Và điểm cộng của em này là không chứa cồn khô, hương liệu, paraben, và màu tổng hợp, vì vậy rất phù hợp với những làn da nhạy cảm nhé.',null,'Clinique Take The Day Off Cleansing Balm')
Insert Into Product VALUES('1bfce16a-802d-455c-9aee-271d0ef9d66e',N'Sáp tẩy trang đến từ thương hiệu Banila Co của Hàn Quốc .Tẩy trang dạng sáp, khi thoa lên mặt sẽ tan trên mặt và hòa tan lớp bụi bẩn và makeup, giúp da tẩy trang sạch nhưng không gây khô da - đặc biệt phù hợp cho các bạn da rất khô.Thành phần ngoài các chất làm sạch, còn có một số dưỡng chất cho da như chiết xuất Tre và các chất làm mềm da như Ethylhexyl Palmitate',null,'Clean It Zero Cleansing Balm Original')
Insert Into Product VALUES('14c44181-444c-4611-a35c-036047acaee5',N'Sản phẩm này là gel hỗ trợ trị mụn và làm sáng da với hoạt chất 20% Azelaic Acid của một hãng mỹ phẩm Alcom đến từ Việt Nam. Azelaic Acid là một thành phần rất hiệu quả để trị mụn nhẹ - vừa và làm sáng da. Bên cạnh đó, một đặc điểm của Azelaic Acid là nhẹ dịu nên khả năng dung nạp vào da khá tốt. Sản phẩm treatment dạng gel nên có thể hơi khô da, bạn nên sử dụng kem dưỡng sau sản phẩm để cấp ẩm và dưỡng ẩm cho da. Đây là một trong những sản phẩm giá "sinh viên" nhưng rất hiệu quả. Đặc biệt là nồng độ Azelaic acid 20% khá khó tìm nên đây là một lựa chọn khá tốt cho các bạn nào muốn thử Azelaic Acid nồng độ này nhé.',null,'Alcom Derma Forte Azelaic acid 20%')
Insert Into Product VALUES('7bc2fce3-ba2a-4d0b-9b29-00c355e8f835',N'Miếng dán siêu mỏng với độ bám dính cao, tạo lớp màng bảo vệ mụn khỏi các tác nhân bên ngoài, giúp kháng khuẩn mụn, giảm đỏ.Salicylic Acid (2%) làm mềm nhân mụn, tróc lớp sừng, giúp nhân mụn thoát ra dễ dàng Vùng da mụn được cải thiện nhanh chóng, giảm nguy cơ để lại sẹo & vết thâm sau mụn',null,N'Acnes Clear Patch–Miếng Dán Mụn')
Insert Into Product VALUES('23c03279-4d48-413c-a6a7-3e533b5aaf40',N'Kem lót Baby Skin Pore Eraser giúp làm mịn da, che khuyết điểm, tạo hiệu ứng lỗ chân lông thu nhỏ, cho lớp nền mịn màng hoàn hảo. Cấu trúc gel trong suốt, mịn nhẹ dễ tán, hiệu quả trong việc che lỗ chân lông ngay tức thì. Hứa hẹn sẽ mang lại làn da láng mịn như da em bé trong tíc tắc.',null,N'Kem Lót Maybelline Baby Skin Mịn Da 22Ml')
Insert Into Product VALUES('29d31e19-036e-4a0b-9fa2-3af4aa0bf79c',N'Kem Lót Kiềm Dầu Zeesea Living Colorfully Multi - Effect Makeup Primer 30g [ Nội Địa Trung] có chết kem lỏng nên rất dễ tán trên da, đồng thời giúp giữ cho da hạn chế đổ dầu hay bết dính ở mức độ cao, mang đến cho bạn cảm giác như đang tận hưởng loại kem dưỡng ẩm yêu thích của mình.',null,N'Kem Lót Kiềm Dầu Zeesea Living Colorfully Multi - Effect Makeup Primer 30g [Nội Địa Trung]')
Insert Into Product VALUES('42169445-a6c4-452b-9e6b-155bfa04ef3a',N'Kem nền mịn da dạng lỏng LOreal Paris True Match Liquid Foundation 30ml chứa các hạt phấn dạng lỏng siêu mịn với công nghệ Micro-Matching che phủ hoàn hảo đem lại cho bạn làn da mịn màng tươi sáng tự nhiên. Ngoài ra với khả năng chống nắng lên đến SPF16 giúp bảo vệ làn da trước mọi ảnh hưởng của ánh nắng mặt trời. Sản phẩm có tông màu phù hợp với làn da châu Á, mang lại cho bạn lớp trang điểm nền hoàn hảo.',null,N'Kem Nền Dưỡng Ẩm Loreal True Match Super Blendable Foundation 30ml')
Insert Into Product VALUES('601261d5-c8cf-4b62-8794-d01d31a1b2d0',N'Kem nền Fit Me gây ấn tượng với khả năng kiềm dầu cho lớp nền mịn lì tự nhiên, đồng thời che phủ tốt mọi khuyết điểm trên bề mặt da và che phủ hoàn hảo lỗ chân lông. Dòng kem nền Fit Me có 12 tông màu phù hợp, tiệp mọi tông da phụ nữ Việt Nam.',null,N'Kem Nền Mịn Nhẹ Kiềm Dầu Fit Me Maybelline New York Matte Poreless Foundation 30ml')
Insert Into Product VALUES('197518f5-6e2b-47d7-a8d2-8b27980b8f44',N'Supermatte Cushion là phấn nước được nghiên cứu dành cho làn da dầu, da siêu dầu và da dầu mụn nhờ có lớp màng cực kỳ bền vững, kiểm soát dầu thừa hữu hiệu, hạn chế vỡ hay chảy nền do mồ hôi và bã nhờn dư thừa. Do đó, lớp nền của bạn sẽ bền chắc, ít xuống màu và lâu trôi.',null,N'Phấn nước siêu kiềm dầu Lemonade Supermatte Cushion 15g')
Insert Into Product VALUES('26a4a2e2-a60d-4234-83c4-f768b6c7764a',N'Phấn Nước Che Khuyết Điểm Clio Kill Cover Mesh Glow Cushion [ Kèm Lõi ] là phấn nước che khuyết điểm phiên bản mới nhất cho năm 2022 và được đánh giá cao về khả năng che phủ và dưỡng ẩm lên đến 24 giờ. Phấn Nước Che Khuyết Điểm Clio cho lớp trang điểm trông bóng khỏe và rạng rỡ, và làn da ẩm mượt như được xịt khoáng. Em phấn nước này sở hữu đầy đủ các tính năng cơ bản như làm trắng, chống tia cực tím, chống nhăn.',null,N'Phấn Nước Che Khuyết Điểm Clio Kill Cover Mesh Glow Cushion')
Insert Into Product VALUES('57b3448b-067f-4f47-9ea6-a01d94baa5e1',N'Che Khuyết Điểm Maybelline Instant Age Rewind Treatment Concealer là kem che khuyết điểm dành cho vùng dưới mắt với thành phần có chứa Haloxyl có khả năng che phủ quầng thâm và bọng mắt một cách hiệu quả, đồng thời tạo sức sống cho gương mặt.',null,N'Kem Che Khuyết Điểm Maybelline Instant Age Rewind Eraser Multi-Use Concealer')
Insert Into Product VALUES('39e3b909-5b38-4158-a3dd-331bdb6bcfe3',N'Kem Che Khuyết Điểm Kiềm Dầu Lemonade Matte Addict Concealer là dòng kem che khuyết điểm của thương hiệu Lemonade, có khả năng che phủ tốt, kiềm dầu và bền màu cực tốt, kết cấu mỏng nhẹ tạo lớp nền lì mịn hoàn hảo, giúp bản che phủ các khuyết điểm trên khuôn mặt. Đặc biệt, sản phẩm có chứa chiết xuất hoa cúc La mã có tác dụng kháng viêm và làm dịu da bị mụn, có thể yên tâm sử dụng cho da mụn và da nhạy cảm.',null,N'Kem Che Khuyết Điểm Kiềm Dầu Lemonade Matte Addict Concealer')
Insert Into Product VALUES('12eda105-52fb-49cd-8dc8-9d1655880b2b',N'Phấn Phủ Kiềm Dầu Dạng Bột Khoáng innisfree No Sebum Mineral Powder là sản phẩm phấn phủ đến từ thương hiệu mỹ phẩm innisfree của Hàn Quốc với chiết xuất từ bạc hà và khoáng chất tự nhiên Jeju, kiềm dầu đồng thời tạo độ che phủ tự nhiên cho lớp nền khô thoáng.',null,N'Phấn Phủ innisfree Kiềm Dầu Dạng Bột Khoáng 5g')
Insert Into Product VALUES('4582529f-e9d8-45d1-bc0d-e180b7822d85',N'Phấn Phủ Mịn Lì Kiềm Dầu Fit Me Matte Poreless Powder Maybelline New York có kết cấu phấn mỏng nhẹ, phấn nền sẽ giúp làn da dù trang điểm nhưng vẫn luôn thông thoáng và không sợ bí da, bít lỗ chân lông. Cấu trúc hạt phấn mịn cho làn da hiệu ứng mịn màng đầy tự nhiên. Hiệu ứng lì cao mang lại lớp nền tươi tắn, rạng rỡ.',null,N'Phấn Phủ Maybelline Mịn Lì Kiềm Dầu 110 Porcelain 8.5g')
Insert Into Product VALUES('29adb9bf-8d66-4e39-9c60-ee3e45a07e7a',N'Xịt Khoáng - Khóa Nền - Cố Định Lớp Trang Điểm Pramy sử dụng sau khi hoàn thành các bước make up giúp kiểm soát dầu nhờn, giúp lớp trang điểm bám lâu hơn, ít xuống màu và bền màu hơn. Sản phẩm cũng chứa chiết xuất lô hội, dưa chuột giúp tăng cường dưỡng ẩm cho da, tạo hiệu ứng lớp nền căng mướt.',null,N'Xịt cố định lớp trang điểm PRAMY kiềm dầu lâu trôi dưỡng ẩm tiện lợi')
Insert Into Product VALUES('4491dfcd-2181-49d9-9afc-6da75eb478b9',N'Chai Xịt 3CE Cố Định Lớp Trang Điểm 100ml là sản phẩm xịt khoá trang điểm đến từ thương hiệu trang điểm 3CE của Hàn Quốc, bên cạnh công dụng dưỡng ẩm, làm dịu da sản phẩm còn giúp giữ lớp nền bền vững, ngăn mồ hồi, dầu thừa đem lại làn da căng bóng tự nhiên và khoẻ mạnh. Đặc biệt sản phẩm có nhũ trắng nhẹ nhàng tạo lớp nền bắt sáng và lấp lánh.',null,N'Xịt Khoá Makeup 3CE Có Nhũ Tạo Hiệu Ứng Nền Căng Bóng 100ml')
Insert Into Product VALUES('50b2dfd7-ec2c-4a26-b3cd-3986bb40dd3d',N'Lấy ý tưởng từ hình khối hội họa với các góc sáng tối bắt mắt, thương hiệu Too Cool For School đã cho ra đời dòng phấn tạo khối với 3 tông màu khác biệt phù hợp với từng vùng trên khuôn mặt, tạo nên sự hài hòa tổng thể của đường nét.',null,N'Phấn Tạo Khối Too Cool For School 01 Màu Đậm 9.5g')
Insert Into Product VALUES('026be434-dac5-47e6-83bc-69a321b4092c',N'SILKYGIRL Photosharp Contour & Highlighter chuyên dành cho các cô nàng Châu Á, với thành phần chiết xuất từ Bisabolol - tinh dầu hoa cúc phù hợp cho cả làn da nhạy cảm. Đầu contour - tạo khối giúp làm thon gọn và chiêu sâu ngay cho gương mặt, bạn sẽ dễ dàng sở hữu khuôn mặt V-line trong tích tắc. Bên cạnh đó, đây còn là biện pháp hữu hiệu khắc phục các đường nét hạn chế như nọng cằm, má, trán... Đầu còn lại là Highlighter có khả năng bắt sáng, tạo sóng mũi cao ngay tức thì cùng hiệu ứng ánh kim ngọc trai thích hợp cho mọi phong cách makeup. Đồng thời, hiệu ứng highlight còn che bớt các vùng da thâm sạm, mệt mỏi trở nên rạng rỡ, làm dày môi và có thể kết hợp cùng chì kẻ mày giúp định hình lông mày đấy nhé!',null,N'')
Insert Into Product VALUES('6cbe9203-6005-4f22-ad49-68b65e254567',N'Má Hồng Dạng Lỏng Ofélia Lolli Liquid Blush thuộc dòng sản phẩm Lolli có kết cấu dạng kem lỏng, mỏng nhẹ và mềm mịn giúp bạn dễ dàng tán đều lên da, tạo hiệu ứng màu trong trẻo, tự nhiên cho gương mặt tươi tắn rạng ngời. Đặc biệt sản phẩm có mùi dưa hấu thơm mát, phù hợp khi sử dụng ngày hè với hương thơm tươi mới của tự nhiên.',null,N'Má Hồng Dạng Lỏng Ofélia Lolli Liquid Blush')
Insert Into Product VALUES('c130275b-3773-434a-a7be-776584954cae',N'Những hộp phấn má hồng nhỏ xinh tưởng chừng như không cần thiết nhưng lại rất quan trọng để bạn có được vẻ ngoài rạng rỡ hoàn hảo. Đôi khi chỉ cần dặm nhẹ chút phấn nước mỏng, thoa chút son, điểm xuyết thêm chút má hồng là bạn đã "nâng tầm" nhan sắc của mình hơn rất nhiều rồi đấy. Hasaki xin giới thiệu với các bạn dòng phấn má hồng dạng nén Maybelline Fit Me Mono Blush với 4 tông màu nhẹ nhàng trẻ trung được chọn lọc phù hợp với tông da châu Á, chất phấn mịn màng dễ tán cùng khả năng kiềm dầu, giúp giữ da bạn luôn khô thoáng, không bóng nhờn. Đây là sản phẩm thích hợp để đồng hành cùng các bạn nữ mỗi ngày, mang đến vẻ ngoài tươi tắn tự nhiên. Các tông màu đang có tại Hasaki:',null,N'Phấn Má Hồng Maybelline Màu Hồng Đào 40 Peach 4.5g')
Insert Into Product VALUES('137a9446-db15-4bd5-a856-c9963cc41b41',N'Sản phẩm có công dụng chính tạo khối, nâng cơ mặt, giúp gương mặt có chiều sâu và nổi bật hơn. Sản phẩm có kết cấu dạng phấn mềm, bám mỏng nhẹ, tạo ra ánh sáng tự nhiên tinh tế tùy thuộc vào góc độ ánh sáng. Kích thước nhỏ gọn, có thể dễ dàng thuận tiện mang đi khi di chuyển nhiều.',null,N'Phấn Bắt Sáng 3CE Glow Beam Xinh Xắn 8,5g')
Insert Into Product VALUES('fbd16326-11d0-486d-8754-154e3e22f9a0',N'Không chỉ làm tốt vai trò “bắt sáng" như tên gọi, Phấn Bắt Sáng Peripera Pure Glory Highlighter còn giúp bạn tạo khối gương mặt, che khuyết điểm và cải thiện các bộ phận khác trên gương mặt như sóng mũi, chân mày, môi.',null,N'Phấn Bắt Sáng Peripera Pure Glory Highlighter')
Insert Into Product VALUES('34767d11-4c5f-4f3b-803f-1d448c131ec6',N' Kết cấu của Paula’s Choice dạng như gel cream giúp dễ dàng tán đều sản phẩm lên da hơn. Đối với các sản phẩm dạng peeling thì một rủi ro có thể gặp phải là các sản phẩm lỡ dính vào phần mắt hay các phần trên da đang bị nhạy cảm - điều này khá dễ xảy ra với sản phẩm peel da khác có trên thị trường như red peel,... còn Paulas Choice dạng gel nên rất dễ tán đều lên da. Bên cạnh acid, sản phẩm Paulas choice còn chứa các chất làm dịu da như chiết xuất hoa đậu biếc, chiết xuất cam thảo, Bisabolol, Allantoin để giúp giảm thiểu tác động không mong muốn trong lúc peel như ngứa, rát. Thời gian peel của em này thì được hãng hưỡng dẫn là khoảng 8 - 10 phút, tuy nhiên đối với một số làn da nhạy cảm thì các bạn có thể giảm thời gian xuống khoảng 3 - 5 phút nhé, để tránh bị kích ứng. Có điều, em này khá đắt hơn, so với những sản phẩm khác trên thị trường, nên cũng sẽ khó tiếp cận với người tiêu dùng.',null,' Paulas Choice 25% AHA + 2% BHA Exfoliant Peel')
Insert Into Product VALUES('8165def7-4c21-4464-b7ed-1175bdc0dec4',N' Kem trị sẹo Scar Esthetique là sản phẩm đến từ tập đoàn dược phẩm nổi tiếng của Mỹ – Atlantic Medical Products. Thành phần chủ yếu được chiết xuất từ thiên nhiên an toàn, lành tính và tốt cho sự phục hồi và tái tạo da. Sản phẩm tác động trực tiếp lên các mô sẹo, làm cấu trúc sẹo mềm lại và căng ra. Đồng thời, các dưỡng chất sẽ thẩm thấu vào bên trong lớp tế bào, kích thích tăng sinh các tế bào nguyên bào sợi, … từ đó làm đầy vết sẹo lõm, sẹo rỗ hiệu quả. Thành phần chính gồm Laminaria từ rong biển với cơ chế tác dụng lên phần ngoài của sẹo giúp làm mềm da, căng mịn da. Chiết xuất hành tây giúp giảm viêm, chống nhiễm trùng. Arnica Extract giúp vận chuyển dinh dưỡng, trao đổi chất, giảm sưng đỏ, giảm thâm, làm sáng da.',null,' Scar Esthetique Scar Cream with Silicone')
Insert Into Product VALUES('e9a1f0d7-3143-4010-b24f-41f89558af20',N' Bioderma Atoderm Crème là sản phẩm kem dưỡng ẩm chăm sóc hàng ngày, bảo vệ và dưỡng ẩm chuyên sâu đến từ thương hiệu dược mỹ phẩm Bioderma của Pháp. Nhờ các thành phần dưỡng chất và tái cấu trúc, kem dưỡng Atoderm Crème giúp tăng cường hàng rào sinh học bảo vệ da và do đó ngăn ngừa các tác nhân gây kích ứng xâm nhập. Với các thành phần dưỡng ẩm, Atoderm Crème giữ nước ở lớp da trên và ngăn chặn quá trình bay hơi.',null,' Bioderma Atoderm Crème')
Insert Into Product VALUES('344b13e7-7836-431a-8ac0-3a78af53f354',N' Kem dưỡng đến từ thương hiệu mỹ phẩm Skin1004 của Hàn Quốc, thành phần chứa 72% chiết xuất rau má cùng với 4 loại Ceramide có nguồn gốc từ thực vật làm dịu làn da mụn, kích ứng, giúp tăng cường hàng rào bảo vệ da, nuôi dưỡng làn da khỏe mạnh. Kết cấu dạng gel mỏng nhẹ như nước cùng khả năng hạ nhiệt độ tức thì và thấm cực nhanh vào sâu từng lớp biểu bì da, vỗ về làn da đang đỏ rát, kích ứng hay tổn thương do mụn trở lại trạng thái ổn định và mềm mịn hơn.',null,N' Kem Dưỡng Skin1004 Madagascar Centella Soothing Dưỡng Ẩm Phục Hồi Da 75ml')
Insert Into Product VALUES('b31fb34c-bc2a-412a-baf3-49da1e56de25',N'Kem Dưỡng Ẩm CeraVe Moisturising Cream Dành Cho Da Khô 50ml giúp duy trì độ ẩm và phục hồi lớp hàng rào bảo vệ cho da mặt và toàn thân với sự kết hợp của 3 Ceramides thiết yếu và Hyaluronic acid. Công thức hấp thụ nhanh và không gây cảm giác nhờn hoặc nặng trên da của bạn.',null,N'Kem Dưỡng Ẩm CeraVe Moisturising Cream Dành Cho Da Khô 50ml')
Insert Into Product VALUES('1ccadc99-5f87-4287-893d-dcedb62286e9',N'Kem Dưỡng La Roche Posay Phục Hồi và Làm Dịu Da Cicaplast Baume B5 100ml thuộc dòng sản phẩm Cicaplast chuyên biệt cho từng vùng da nhạy cảm & thương tổn, giúp phục hồi, tái tạo làn da. Sản phẩm kem dưỡng đa năng giúp làm dịu và bảo vệ làn da bị kích ứng, có thể sử dụng cho trẻ em và người lớn.',null,N'Kem Dưỡng La Roche-Posay B5+ Phục Hồi Da 100ml')
Insert Into Product VALUES('3361dbec-b864-4c3e-8b47-dd55cdf218d5',N'Kem Dưỡng Dear Klairs Làm Dịu Và Phục Hồi Da Midnight Blue Calming Cream 60ml giúp phục hồi và làm dịu da khi bị kích ứng, phục hồi da sau điều trị (lazer, tẩy da chết), làm giảm sưng tấy vết thương sau khi trị mụn hoặc lấy nhân. Sản phẩm còn giúp lấy lại sức sống cho làn da đối với những người làm việc văn phòng, chịu nhiều áp lực, thúc đẩy phục hồi da sau tổn thương. Chất kem đặc màu xanh dương bắt mắt khiến người dùng có cảm giác tươi mát ngay khi nhìn thấy sản phẩm.',null,N'Kem Dưỡng Dear Klairs Làm Dịu Và Phục Hồi Da Midnight Blue Calming Cream 60ml')
Insert Into Product VALUES('95d9d78d-4467-4feb-ae75-ae34093fa3d7',N'Gel Dưỡng Gamma Megaduo Plus Giảm Mụn, Giảm Thâm 15g với thành phần chính là Retinal 1.0 và AHA giúp xua tan nỗi lo về mụn và vết thâm, ngăn ngừa mụn trứng cá, mụn đầu đen, mụn đầu trắng, mụn kèm theo viêm bội nhiễm từ trung bình đến nặng và dưỡng da.',null,N'Gel Dưỡng Megaduo Plus Giảm Mụn, Mờ Thâm 15g')
Insert Into Product VALUES('8ace548d-761a-4dcd-9340-176eea76e7a7',N'Tinh Chất Garnier Giảm Mụn Mờ Thâm Cho Da Dầu, Mụn 30ml là sản phẩm serum đến từ thương hiệu mỹ phẩm Garnier của Pháp, với công thức vượt trội 4% phức hợp Vitamin C, BHA, Niacinamide, AHA có công dụng giảm mụn, mờ vết thâm và vết thâm do mụn đồng thời làn da sẽ được làm dịu, sáng hơn rõ rệt. Sản phẩm hoạt động theo cơ chế 3 tác động làm giảm bã nhờn - tiêu sừng - mờ thâm mang lại làn da sáng mịn, rạng ngời.',null,N'Serum Garnier Giảm Mụn Mờ Thâm Cho Da Dầu, Mụn 30ml')
Insert Into Product VALUES('82261e8d-6443-45d7-ae64-cfc95241bca6',N'Serum trắng da, mờ thâm Balance Active Formula Vitamin C Brightening 30ml với thành phần chính là Vitamin C nhưng tối ưu hơn nhờ các dạng thức ổn định và hiệu quả nhất của Vitamin C.',null,'Brightening Serum Balance Active Formula 30Ml')
Insert Into Product VALUES('e6314cec-f4f3-4b7c-ad6d-730f50bf3de6',N'Tinh Chất La Roche-Posay Giảm Thâm Nám & Làm Đều Màu Da 30ml là sản phẩm serum đến từ thương hiệu dược mỹ phẩm nổi tiếng La Roche-Posay của Pháp, chứa các thành phần ưu việt trong dưỡng da với 0.3% Retinol, cùng 2% vitamin B3 (Niacinamide) và 10% Glycerin giúp làm giảm nếp nhăn, hạn chế các dấu hiệu lão hoá da đồng thời làm sáng và đều màu da, ngăn hình thành các đốm sắc tố tối màu da. Đặc biệt sản phẩm với công thức an toàn trên mọi làn da, kể cả da nhạy cảm.',null,N'Serum La Roche-Posay Giúp Giảm Thâm Nám, Làm Đều Màu Da 30ml')
Insert Into Product VALUES('fbedb0d2-b839-4482-832f-73f34b1548ec',N'Tinh Chất Klairs Vitamin C Dưỡng Sáng Da, Mờ Thâm 35ml là sản phẩm tinh chất đến từ thương hiệu Klairs của Hàn Quốc, tiếp thêm sinh lực trẻ hóa làn da với sức mạnh của 5% Vitamin C dạng Acid L-ascorbic nhẹ dịu; cùng chiết xuất Rau Má không gây kích ứng nhưng vẫn hiệu quả trong việc làm mờ các vết mụn và vết nám, cải thiện làn da xỉn và không đều màu.',null,N'Serum Klairs Vitamin C Cho Da Nhạy Cảm 35ml')
Insert Into Product VALUES('aa6cb1bc-51a2-493b-8a5a-a5ffceff697c',N' Là sản phẩm Tretinoin của hãng dược mỹ phẩm Galderma (Thụy sĩ), Retacnyl cũng là một sản phẩm Tretinoin khá phổ biến. Một điểm khác biệt của Retacnyl là sản phẩm chứa nhiều thành phần hơn đa phần các sản phẩm Tretinoin khác (Retin-A, Obagi), đa dạng hơn các chất chống Oxy hóa và làm mềm, dưỡng ẩm da giúp da dễ dung nạp Tretinoin hơn. Tuy vậy, nhiều thành phần hơn đồng nghĩa với việc khả năng có thể kích ứng cao hơn các Tretinoin khác. Bạn nên patch test trước để an toàn.',null,' Galderma Retacnyl Tretinoin Cream 0.025%')

---- Product Skin Type Table ----
---- 1. Da hỗn hợp / 2. Da bình thường / 3. Da dầu / 4. Tất cả / 5. Da khô / 6. Da nhạy cảm ----

GO
Insert Into ProductSkinType VALUES(null, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835', 1)
Insert Into ProductSkinType VALUES(null, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835', 2)
Insert Into ProductSkinType VALUES(null, '14C44181-444C-4611-A35C-036047ACAEE5', 5)
Insert Into ProductSkinType VALUES(null, '14C44181-444C-4611-A35C-036047ACAEE5', 6)
Insert Into ProductSkinType VALUES(null, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4', 3)
Insert Into ProductSkinType VALUES(null, 'FBD16326-11D0-486D-8754-154E3E22F9A0', 5)
Insert Into ProductSkinType VALUES(null, 'FBD16326-11D0-486D-8754-154E3E22F9A0', 1)
Insert Into ProductSkinType VALUES(null, 'FBD16326-11D0-486D-8754-154E3E22F9A0', 2)
Insert Into ProductSkinType VALUES(null, '42169445-A6C4-452B-9E6B-155BFA04EF3A', 5)
Insert Into ProductSkinType VALUES(null, '42169445-A6C4-452B-9E6B-155BFA04EF3A', 1)
Insert Into ProductSkinType VALUES(null, '42169445-A6C4-452B-9E6B-155BFA04EF3A', 2)
Insert Into ProductSkinType VALUES(null, '8ACE548D-761A-4DCD-9340-176EEA76E7A7', 4)
Insert Into ProductSkinType VALUES(null, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC', 4)
Insert Into ProductSkinType VALUES(null, '34767D11-4C5F-4F3B-803F-1D448C131EC6', 4)
Insert Into ProductSkinType VALUES(null, '1BFCE16A-802D-455C-9AEE-271D0EF9D66E', 4)
Insert Into ProductSkinType VALUES(null, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249', 3)
Insert Into ProductSkinType VALUES(null, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249', 1)
Insert Into ProductSkinType VALUES(null, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249', 5)
Insert Into ProductSkinType VALUES(null, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249', 2)
Insert Into ProductSkinType VALUES(null, '39E3B909-5B38-4158-A3DD-331BDB6BCFE3', 4)
Insert Into ProductSkinType VALUES(null, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D', 4)
Insert Into ProductSkinType VALUES(null, '344B13E7-7836-431A-8AC0-3A78AF53F354', 4)
Insert Into ProductSkinType VALUES(null, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C', 1)
Insert Into ProductSkinType VALUES(null, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C', 5)
Insert Into ProductSkinType VALUES(null, '23C03279-4D48-413C-A6A7-3E533B5AAF40', 2)
Insert Into ProductSkinType VALUES(null, '23C03279-4D48-413C-A6A7-3E533B5AAF40', 3)
Insert Into ProductSkinType VALUES(null, 'E9A1F0D7-3143-4010-B24F-41F89558AF20', 4)
Insert Into ProductSkinType VALUES(null, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25', 2)
Insert Into ProductSkinType VALUES(null, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25', 1)
Insert Into ProductSkinType VALUES(null, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25', 5)
Insert Into ProductSkinType VALUES(null, '6CBE9203-6005-4F22-AD49-68B65E254567', 4)
Insert Into ProductSkinType VALUES(null, '026BE434-DAC5-47E6-83BC-69A321B4092C', 4)
Insert Into ProductSkinType VALUES(null, '4491DFCD-2181-49D9-9AFC-6DA75EB478B9', 4)
Insert Into ProductSkinType VALUES(null, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6', 5)
Insert Into ProductSkinType VALUES(null, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6', 3)
Insert Into ProductSkinType VALUES(null, 'FBEDB0D2-B839-4482-832F-73F34B1548EC', 5)
Insert Into ProductSkinType VALUES(null, 'C130275B-3773-434A-A7BE-776584954CAE', 2)
Insert Into ProductSkinType VALUES(null, 'BD7653AF-238D-4762-BB89-77BF94C5941E', 1)
Insert Into ProductSkinType VALUES(null, 'BD7653AF-238D-4762-BB89-77BF94C5941E', 2)
Insert Into ProductSkinType VALUES(null, '816BF9E3-2730-49A6-99CC-889C047E42A3', 3)
Insert Into ProductSkinType VALUES(null, '816BF9E3-2730-49A6-99CC-889C047E42A3', 2)
Insert Into ProductSkinType VALUES(null, '816BF9E3-2730-49A6-99CC-889C047E42A3', 1)
Insert Into ProductSkinType VALUES(null, '197518F5-6E2B-47D7-A8D2-8B27980B8F44', 4)
Insert Into ProductSkinType VALUES(null, '91918E2B-5832-46B8-9842-9841197BCA79', 4)
Insert Into ProductSkinType VALUES(null, '12EDA105-52FB-49CD-8DC8-9D1655880B2B', 4)
Insert Into ProductSkinType VALUES(null, '57B3448B-067F-4F47-9EA6-A01D94BAA5E1', 5)
Insert Into ProductSkinType VALUES(null, '57B3448B-067F-4F47-9EA6-A01D94BAA5E1', 1)
Insert Into ProductSkinType VALUES(null, 'AA6CB1BC-51A2-493B-8A5A-A5FFCEFF697C', 5)
Insert Into ProductSkinType VALUES(null, 'AA6CB1BC-51A2-493B-8A5A-A5FFCEFF697C', 2)
Insert Into ProductSkinType VALUES(null, '95D9D78D-4467-4FEB-AE75-AE34093FA3D7', 1)
Insert Into ProductSkinType VALUES(null, '95D9D78D-4467-4FEB-AE75-AE34093FA3D7', 3)
Insert Into ProductSkinType VALUES(null, '23B71D2A-DBE5-4C16-916C-BB63DFD2D383', 2)
Insert Into ProductSkinType VALUES(null, 'F9958782-9B00-4B5D-A8B6-C6961D2AE039', 4)
Insert Into ProductSkinType VALUES(null, '137A9446-DB15-4BD5-A856-C9963CC41B41', 2)
Insert Into ProductSkinType VALUES(null, '137A9446-DB15-4BD5-A856-C9963CC41B41', 1)
Insert Into ProductSkinType VALUES(null, '82261E8D-6443-45D7-AE64-CFC95241BCA6', 4)
Insert Into ProductSkinType VALUES(null, '82261E8D-6443-45D7-AE64-CFC95241BCA6', 2)
Insert Into ProductSkinType VALUES(null, '1CCADC99-5F87-4287-893D-DCEDB62286E9', 2)
Insert Into ProductSkinType VALUES(null, '3361DBEC-B864-4C3E-8B47-DD55CDF218D5', 2)
Insert Into ProductSkinType VALUES(null, '3361DBEC-B864-4C3E-8B47-DD55CDF218D5', 3)
Insert Into ProductSkinType VALUES(null, '4582529F-E9D8-45D1-BC0D-E180B7822D85', 1)
Insert Into ProductSkinType VALUES(null, '1EA9BFE9-8736-44DC-AFBB-E463CAB9FC5C', 1)
Insert Into ProductSkinType VALUES(null, '29ADB9BF-8D66-4E39-9C60-EE3E45A07E7A', 2)
Insert Into ProductSkinType VALUES(null, '29ADB9BF-8D66-4E39-9C60-EE3E45A07E7A', 3)
Insert Into ProductSkinType VALUES(null, '29ADB9BF-8D66-4E39-9C60-EE3E45A07E7A', 5)
Insert Into ProductSkinType VALUES(null, '26A4A2E2-A60D-4234-83C4-F768B6C7764A', 1)
Insert Into ProductSkinType VALUES(null, '26A4A2E2-A60D-4234-83C4-F768B6C7764A', 5)
Insert Into ProductSkinType VALUES(null, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF', 1)
Insert Into ProductSkinType VALUES(null, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF', 2)
Insert Into ProductSkinType VALUES(null, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF', 5)

---- Product Category Table ----
---- 1. Sữa rửa mặt / 2. Tẩy trang / 3.Đặc trị / 4. Kem dưỡng ẩm / 5.Kem lót ----
---- 6. Kem nền / 7. Cushion / 8. Che khuyết điểm / 9. Phấn phủ / 10. Xịt khóa makeup ----
---- 11. Tạo khối / 12. Má hồng / 13. Highlight / 14. Khác ----

GO
Insert Into ProductCategory VALUES(null, 14, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835')
Insert Into ProductCategory VALUES(null, 14, '14C44181-444C-4611-A35C-036047ACAEE5')
Insert Into ProductCategory VALUES(null, 3, '14C44181-444C-4611-A35C-036047ACAEE5')
Insert Into ProductCategory VALUES(null, 14, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4')
Insert Into ProductCategory VALUES(null, 13, 'FBD16326-11D0-486D-8754-154E3E22F9A0')
Insert Into ProductCategory VALUES(null, 6, '42169445-A6C4-452B-9E6B-155BFA04EF3A')
Insert Into ProductCategory VALUES(null, 3, '8ACE548D-761A-4DCD-9340-176EEA76E7A7')
Insert Into ProductCategory VALUES(null, 1, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC')
Insert Into ProductCategory VALUES(null, 14, '34767D11-4C5F-4F3B-803F-1D448C131EC6')
Insert Into ProductCategory VALUES(null, 10, '1BFCE16A-802D-455C-9AEE-271D0EF9D66E')
Insert Into ProductCategory VALUES(null, 2, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249')
Insert Into ProductCategory VALUES(null, 8, '39E3B909-5B38-4158-A3DD-331BDB6BCFE3')
Insert Into ProductCategory VALUES(null, 11, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D')
Insert Into ProductCategory VALUES(null, 3, '344B13E7-7836-431A-8AC0-3A78AF53F354')
Insert Into ProductCategory VALUES(null, 5, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C')
Insert Into ProductCategory VALUES(null, 5, '23C03279-4D48-413C-A6A7-3E533B5AAF40')
Insert Into ProductCategory VALUES(null, 4, 'E9A1F0D7-3143-4010-B24F-41F89558AF20')
Insert Into ProductCategory VALUES(null, 4, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25')
Insert Into ProductCategory VALUES(null, 12, '6CBE9203-6005-4F22-AD49-68B65E254567')
Insert Into ProductCategory VALUES(null, 14, '026BE434-DAC5-47E6-83BC-69A321B4092C')
Insert Into ProductCategory VALUES(null, 10, '4491DFCD-2181-49D9-9AFC-6DA75EB478B9')
Insert Into ProductCategory VALUES(null, 3, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6')
Insert Into ProductCategory VALUES(null, 3, 'FBEDB0D2-B839-4482-832F-73F34B1548EC')
Insert Into ProductCategory VALUES(null, 12, 'C130275B-3773-434A-A7BE-776584954CAE')
Insert Into ProductCategory VALUES(null, 2, 'BD7653AF-238D-4762-BB89-77BF94C5941E')
Insert Into ProductCategory VALUES(null, 2, '816BF9E3-2730-49A6-99CC-889C047E42A3')
Insert Into ProductCategory VALUES(null, 7, '197518F5-6E2B-47D7-A8D2-8B27980B8F44')
Insert Into ProductCategory VALUES(null, 2, '91918E2B-5832-46B8-9842-9841197BCA79')
Insert Into ProductCategory VALUES(null, 9, '12EDA105-52FB-49CD-8DC8-9D1655880B2B')
Insert Into ProductCategory VALUES(null, 8, '57B3448B-067F-4F47-9EA6-A01D94BAA5E1')
Insert Into ProductCategory VALUES(null, 3, 'AA6CB1BC-51A2-493B-8A5A-A5FFCEFF697C')
Insert Into ProductCategory VALUES(null, 3, '95D9D78D-4467-4FEB-AE75-AE34093FA3D7')
Insert Into ProductCategory VALUES(null, 2, '23B71D2A-DBE5-4C16-916C-BB63DFD2D383')
Insert Into ProductCategory VALUES(null, 2, 'F9958782-9B00-4B5D-A8B6-C6961D2AE039')
Insert Into ProductCategory VALUES(null, 9, '137A9446-DB15-4BD5-A856-C9963CC41B41')
Insert Into ProductCategory VALUES(null, 3, '82261E8D-6443-45D7-AE64-CFC95241BCA6')
Insert Into ProductCategory VALUES(null, 6, '601261D5-C8CF-4B62-8794-D01D31A1B2D0')
Insert Into ProductCategory VALUES(null, 4, '1CCADC99-5F87-4287-893D-DCEDB62286E9')
Insert Into ProductCategory VALUES(null, 4, '3361DBEC-B864-4C3E-8B47-DD55CDF218D5')
Insert Into ProductCategory VALUES(null, 9, '4582529F-E9D8-45D1-BC0D-E180B7822D85')
Insert Into ProductCategory VALUES(null, 1, '1EA9BFE9-8736-44DC-AFBB-E463CAB9FC5C')
Insert Into ProductCategory VALUES(null, 10, '29ADB9BF-8D66-4E39-9C60-EE3E45A07E7A')
Insert Into ProductCategory VALUES(null, 7, '26A4A2E2-A60D-4234-83C4-F768B6C7764A')
Insert Into ProductCategory VALUES(null, 12, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF')

---- Product Characteristic ----
---- 1. Sản phẩm không chứa cồn / 2. Sản phẩm không chứa chất hương liệu / 3. Sản phẩm không phải là dạng thuốc ----
---- 4. Sản phẩm có thể gây kích thích mụn nám / 5. Sản phẩm không phù hợp cho bà bầu lúc mang thai và cho con bú / 6. Không gây kích ứng ----
---- 7. Không chứa paraben / 8. Không gây mụn / 9. Không xà phòng / 10. Không hương liệu / 11. Không chứa paraben ----
---- 12. Không bít tắc lỗ chân lông / 13. Đã được kiểm nghiệm không gây kích ứng / 14. Sản phẩm không chứa chất bảo quản ----
---- 15. không nhờn rít / 16. Sử dụng vào BAN ĐÊM / 17. Dùng được cho Ban Ngày và Ban Đêm / 18. Hạn chế sử dụng sản phẩm trên các vùng da có vết thương ----

GO
Insert Into ProductCharacteristics VALUES( 1, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835')
Insert Into ProductCharacteristics VALUES( 4, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835')
Insert Into ProductCharacteristics VALUES( 3, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835')
Insert Into ProductCharacteristics VALUES( 5, '7BC2FCE3-BA2A-4D0B-9B29-00C355E8F835')
Insert Into ProductCharacteristics VALUES( 1, '14C44181-444C-4611-A35C-036047ACAEE5')
Insert Into ProductCharacteristics VALUES( 3, '14C44181-444C-4611-A35C-036047ACAEE5')
Insert Into ProductCharacteristics VALUES( 5, '14C44181-444C-4611-A35C-036047ACAEE5')
Insert Into ProductCharacteristics VALUES( 4, '14C44181-444C-4611-A35C-036047ACAEE5')
Insert Into ProductCharacteristics VALUES( 2, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4')
Insert Into ProductCharacteristics VALUES( 1, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4')
Insert Into ProductCharacteristics VALUES( 3, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4')
Insert Into ProductCharacteristics VALUES( 4, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4')
Insert Into ProductCharacteristics VALUES( 5, '8165DEF7-4C21-4464-B7ED-1175BDC0DEC4')
Insert Into ProductCharacteristics VALUES( 1, 'FBD16326-11D0-486D-8754-154E3E22F9A0')
Insert Into ProductCharacteristics VALUES( 6, 'FBD16326-11D0-486D-8754-154E3E22F9A0')
Insert Into ProductCharacteristics VALUES( 7, 'FBD16326-11D0-486D-8754-154E3E22F9A0')
Insert Into ProductCharacteristics VALUES( 1, '42169445-A6C4-452B-9E6B-155BFA04EF3A')
Insert Into ProductCharacteristics VALUES( 5, '42169445-A6C4-452B-9E6B-155BFA04EF3A')
Insert Into ProductCharacteristics VALUES( 8, '42169445-A6C4-452B-9E6B-155BFA04EF3A')
Insert Into ProductCharacteristics VALUES( 9, '42169445-A6C4-452B-9E6B-155BFA04EF3A')
Insert Into ProductCharacteristics VALUES( 17, '8ACE548D-761A-4DCD-9340-176EEA76E7A7')
Insert Into ProductCharacteristics VALUES( 18, '8ACE548D-761A-4DCD-9340-176EEA76E7A7')
Insert Into ProductCharacteristics VALUES( 12, '8ACE548D-761A-4DCD-9340-176EEA76E7A7')
Insert Into ProductCharacteristics VALUES( 1, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC')
Insert Into ProductCharacteristics VALUES( 2, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC')
Insert Into ProductCharacteristics VALUES( 3, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC')
Insert Into ProductCharacteristics VALUES( 6, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC')
Insert Into ProductCharacteristics VALUES( 5, 'AAEBAEDE-6390-42F3-995B-1873AE0BDDCC')
Insert Into ProductCharacteristics VALUES( 1, '34767D11-4C5F-4F3B-803F-1D448C131EC6')
Insert Into ProductCharacteristics VALUES( 2, '34767D11-4C5F-4F3B-803F-1D448C131EC6')
Insert Into ProductCharacteristics VALUES( 3, '34767D11-4C5F-4F3B-803F-1D448C131EC6')
Insert Into ProductCharacteristics VALUES( 5, '34767D11-4C5F-4F3B-803F-1D448C131EC6')
Insert Into ProductCharacteristics VALUES( 4, '34767D11-4C5F-4F3B-803F-1D448C131EC6')
Insert Into ProductCharacteristics VALUES( 3, '1BFCE16A-802D-455C-9AEE-271D0EF9D66E')
Insert Into ProductCharacteristics VALUES( 7, '1BFCE16A-802D-455C-9AEE-271D0EF9D66E')
Insert Into ProductCharacteristics VALUES( 9, '1BFCE16A-802D-455C-9AEE-271D0EF9D66E')
Insert Into ProductCharacteristics VALUES( 10, '1BFCE16A-802D-455C-9AEE-271D0EF9D66E')
Insert Into ProductCharacteristics VALUES( 3, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249')
Insert Into ProductCharacteristics VALUES( 18, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249')
Insert Into ProductCharacteristics VALUES( 16, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249')
Insert Into ProductCharacteristics VALUES( 5, '7E5E1B0D-93F1-4D20-91B9-2F2A9D036249')
Insert Into ProductCharacteristics VALUES( 3, '39E3B909-5B38-4158-A3DD-331BDB6BCFE3')
Insert Into ProductCharacteristics VALUES( 4, '39E3B909-5B38-4158-A3DD-331BDB6BCFE3')
Insert Into ProductCharacteristics VALUES( 7, '39E3B909-5B38-4158-A3DD-331BDB6BCFE3')
Insert Into ProductCharacteristics VALUES( 9, '39E3B909-5B38-4158-A3DD-331BDB6BCFE3')
Insert Into ProductCharacteristics VALUES( 17, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D')
Insert Into ProductCharacteristics VALUES( 18, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D')
Insert Into ProductCharacteristics VALUES( 1, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D')
Insert Into ProductCharacteristics VALUES( 15, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D')
Insert Into ProductCharacteristics VALUES( 13, '50B2DFD7-EC2C-4A26-B3CD-3986BB40DD3D')
Insert Into ProductCharacteristics VALUES( 5, '344B13E7-7836-431A-8AC0-3A78AF53F354')
Insert Into ProductCharacteristics VALUES( 7, '344B13E7-7836-431A-8AC0-3A78AF53F354')
Insert Into ProductCharacteristics VALUES( 3, '344B13E7-7836-431A-8AC0-3A78AF53F354')
Insert Into ProductCharacteristics VALUES( 11, '344B13E7-7836-431A-8AC0-3A78AF53F354')
Insert Into ProductCharacteristics VALUES( 14, '344B13E7-7836-431A-8AC0-3A78AF53F354')
Insert Into ProductCharacteristics VALUES( 18, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C')
Insert Into ProductCharacteristics VALUES( 1, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C')
Insert Into ProductCharacteristics VALUES( 3, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C')
Insert Into ProductCharacteristics VALUES( 5, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C')
Insert Into ProductCharacteristics VALUES( 12, '29D31E19-036E-4A0B-9FA2-3AF4AA0BF79C')
Insert Into ProductCharacteristics VALUES( 1, '23C03279-4D48-413C-A6A7-3E533B5AAF40')
Insert Into ProductCharacteristics VALUES( 3, '23C03279-4D48-413C-A6A7-3E533B5AAF40')
Insert Into ProductCharacteristics VALUES( 5, '23C03279-4D48-413C-A6A7-3E533B5AAF40')
Insert Into ProductCharacteristics VALUES( 12, 'E9A1F0D7-3143-4010-B24F-41F89558AF20')
Insert Into ProductCharacteristics VALUES( 14, 'E9A1F0D7-3143-4010-B24F-41F89558AF20')
Insert Into ProductCharacteristics VALUES( 13, 'E9A1F0D7-3143-4010-B24F-41F89558AF20')
Insert Into ProductCharacteristics VALUES( 13, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25')
Insert Into ProductCharacteristics VALUES( 1, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25')
Insert Into ProductCharacteristics VALUES( 3, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25')
Insert Into ProductCharacteristics VALUES( 5, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25')
Insert Into ProductCharacteristics VALUES( 18, 'B31FB34C-BC2A-412A-BAF3-49DA1E56DE25')
Insert Into ProductCharacteristics VALUES( 17, '6CBE9203-6005-4F22-AD49-68B65E254567')
Insert Into ProductCharacteristics VALUES( 15, '6CBE9203-6005-4F22-AD49-68B65E254567')
Insert Into ProductCharacteristics VALUES( 10, '6CBE9203-6005-4F22-AD49-68B65E254567')
Insert Into ProductCharacteristics VALUES( 8, '6CBE9203-6005-4F22-AD49-68B65E254567')
Insert Into ProductCharacteristics VALUES( 1, '026BE434-DAC5-47E6-83BC-69A321B4092C')
Insert Into ProductCharacteristics VALUES( 5, '026BE434-DAC5-47E6-83BC-69A321B4092C')
Insert Into ProductCharacteristics VALUES( 12, '026BE434-DAC5-47E6-83BC-69A321B4092C')
Insert Into ProductCharacteristics VALUES( 7, '4491DFCD-2181-49D9-9AFC-6DA75EB478B9')
Insert Into ProductCharacteristics VALUES( 5, '4491DFCD-2181-49D9-9AFC-6DA75EB478B9')
Insert Into ProductCharacteristics VALUES( 18, '4491DFCD-2181-49D9-9AFC-6DA75EB478B9')
Insert Into ProductCharacteristics VALUES( 13, '4491DFCD-2181-49D9-9AFC-6DA75EB478B9')
Insert Into ProductCharacteristics VALUES( 11, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6')
Insert Into ProductCharacteristics VALUES( 5, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6')
Insert Into ProductCharacteristics VALUES( 3, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6')
Insert Into ProductCharacteristics VALUES( 4, 'E6314CEC-F4F3-4B7C-AD6D-730F50BF3DE6')
Insert Into ProductCharacteristics VALUES( 18, 'FBEDB0D2-B839-4482-832F-73F34B1548EC')
Insert Into ProductCharacteristics VALUES( 15, 'FBEDB0D2-B839-4482-832F-73F34B1548EC')
Insert Into ProductCharacteristics VALUES( 14, 'FBEDB0D2-B839-4482-832F-73F34B1548EC')
Insert Into ProductCharacteristics VALUES( 5, 'C130275B-3773-434A-A7BE-776584954CAE')
Insert Into ProductCharacteristics VALUES( 8, 'C130275B-3773-434A-A7BE-776584954CAE')
Insert Into ProductCharacteristics VALUES( 9, 'C130275B-3773-434A-A7BE-776584954CAE')
Insert Into ProductCharacteristics VALUES( 1, 'C130275B-3773-434A-A7BE-776584954CAE')
Insert Into ProductCharacteristics VALUES( 11, 'C130275B-3773-434A-A7BE-776584954CAE')
Insert Into ProductCharacteristics VALUES( 4, 'BD7653AF-238D-4762-BB89-77BF94C5941E')
Insert Into ProductCharacteristics VALUES( 5, 'BD7653AF-238D-4762-BB89-77BF94C5941E')
Insert Into ProductCharacteristics VALUES( 15, 'BD7653AF-238D-4762-BB89-77BF94C5941E')
Insert Into ProductCharacteristics VALUES( 1, 'BD7653AF-238D-4762-BB89-77BF94C5941E')
Insert Into ProductCharacteristics VALUES( 16, '816BF9E3-2730-49A6-99CC-889C047E42A3')
Insert Into ProductCharacteristics VALUES( 2, '816BF9E3-2730-49A6-99CC-889C047E42A3')
Insert Into ProductCharacteristics VALUES( 5, '816BF9E3-2730-49A6-99CC-889C047E42A3')
Insert Into ProductCharacteristics VALUES( 11, '816BF9E3-2730-49A6-99CC-889C047E42A3')
Insert Into ProductCharacteristics VALUES( 4, '816BF9E3-2730-49A6-99CC-889C047E42A3')
Insert Into ProductCharacteristics VALUES( 4, '197518F5-6E2B-47D7-A8D2-8B27980B8F44')
Insert Into ProductCharacteristics VALUES( 6, '197518F5-6E2B-47D7-A8D2-8B27980B8F44')
Insert Into ProductCharacteristics VALUES( 15, '197518F5-6E2B-47D7-A8D2-8B27980B8F44')
Insert Into ProductCharacteristics VALUES( 17, '197518F5-6E2B-47D7-A8D2-8B27980B8F44')
Insert Into ProductCharacteristics VALUES( 18, '91918E2B-5832-46B8-9842-9841197BCA79')
Insert Into ProductCharacteristics VALUES( 11, '91918E2B-5832-46B8-9842-9841197BCA79')
Insert Into ProductCharacteristics VALUES( 5, '91918E2B-5832-46B8-9842-9841197BCA79')
Insert Into ProductCharacteristics VALUES( 4, '12EDA105-52FB-49CD-8DC8-9D1655880B2B')
Insert Into ProductCharacteristics VALUES( 1, '12EDA105-52FB-49CD-8DC8-9D1655880B2B')
Insert Into ProductCharacteristics VALUES( 3, '12EDA105-52FB-49CD-8DC8-9D1655880B2B')
Insert Into ProductCharacteristics VALUES( 2, '12EDA105-52FB-49CD-8DC8-9D1655880B2B')
Insert Into ProductCharacteristics VALUES( 12, '57B3448B-067F-4F47-9EA6-A01D94BAA5E1')
Insert Into ProductCharacteristics VALUES( 15, '57B3448B-067F-4F47-9EA6-A01D94BAA5E1')
Insert Into ProductCharacteristics VALUES( 1, '57B3448B-067F-4F47-9EA6-A01D94BAA5E1')
Insert Into ProductCharacteristics VALUES( 2, 'AA6CB1BC-51A2-493B-8A5A-A5FFCEFF697C')
Insert Into ProductCharacteristics VALUES( 4, 'AA6CB1BC-51A2-493B-8A5A-A5FFCEFF697C')
Insert Into ProductCharacteristics VALUES( 5, 'AA6CB1BC-51A2-493B-8A5A-A5FFCEFF697C')
Insert Into ProductCharacteristics VALUES( 11, '95D9D78D-4467-4FEB-AE75-AE34093FA3D7')
Insert Into ProductCharacteristics VALUES( 15, '95D9D78D-4467-4FEB-AE75-AE34093FA3D7')
Insert Into ProductCharacteristics VALUES( 17, '95D9D78D-4467-4FEB-AE75-AE34093FA3D7')
Insert Into ProductCharacteristics VALUES( 4, '23B71D2A-DBE5-4C16-916C-BB63DFD2D383')
Insert Into ProductCharacteristics VALUES( 6, '23B71D2A-DBE5-4C16-916C-BB63DFD2D383')
Insert Into ProductCharacteristics VALUES( 2, 'F9958782-9B00-4B5D-A8B6-C6961D2AE039')
Insert Into ProductCharacteristics VALUES( 5, 'F9958782-9B00-4B5D-A8B6-C6961D2AE039')
Insert Into ProductCharacteristics VALUES( 12, 'F9958782-9B00-4B5D-A8B6-C6961D2AE039')
Insert Into ProductCharacteristics VALUES( 17, '137A9446-DB15-4BD5-A856-C9963CC41B41')
Insert Into ProductCharacteristics VALUES( 15, '137A9446-DB15-4BD5-A856-C9963CC41B41')
Insert Into ProductCharacteristics VALUES( 1, '137A9446-DB15-4BD5-A856-C9963CC41B41')
Insert Into ProductCharacteristics VALUES( 3, '137A9446-DB15-4BD5-A856-C9963CC41B41')
Insert Into ProductCharacteristics VALUES( 5, '137A9446-DB15-4BD5-A856-C9963CC41B41')
Insert Into ProductCharacteristics VALUES( 4, '82261E8D-6443-45D7-AE64-CFC95241BCA6')
Insert Into ProductCharacteristics VALUES( 5, '82261E8D-6443-45D7-AE64-CFC95241BCA6')
Insert Into ProductCharacteristics VALUES( 11, '82261E8D-6443-45D7-AE64-CFC95241BCA6')
Insert Into ProductCharacteristics VALUES( 12, '601261D5-C8CF-4B62-8794-D01D31A1B2D0')
Insert Into ProductCharacteristics VALUES( 5, '601261D5-C8CF-4B62-8794-D01D31A1B2D0')
Insert Into ProductCharacteristics VALUES( 4, '601261D5-C8CF-4B62-8794-D01D31A1B2D0')
Insert Into ProductCharacteristics VALUES( 7, '601261D5-C8CF-4B62-8794-D01D31A1B2D0')
Insert Into ProductCharacteristics VALUES( 12, '1CCADC99-5F87-4287-893D-DCEDB62286E9')
Insert Into ProductCharacteristics VALUES( 15, '1CCADC99-5F87-4287-893D-DCEDB62286E9')
Insert Into ProductCharacteristics VALUES( 18, '1CCADC99-5F87-4287-893D-DCEDB62286E9')
Insert Into ProductCharacteristics VALUES( 1, '3361DBEC-B864-4C3E-8B47-DD55CDF218D5')
Insert Into ProductCharacteristics VALUES( 4, '3361DBEC-B864-4C3E-8B47-DD55CDF218D5')
Insert Into ProductCharacteristics VALUES( 3, '3361DBEC-B864-4C3E-8B47-DD55CDF218D5')
Insert Into ProductCharacteristics VALUES( 2, '4582529F-E9D8-45D1-BC0D-E180B7822D85')
Insert Into ProductCharacteristics VALUES( 4, '4582529F-E9D8-45D1-BC0D-E180B7822D85')
Insert Into ProductCharacteristics VALUES( 5, '4582529F-E9D8-45D1-BC0D-E180B7822D85')
Insert Into ProductCharacteristics VALUES( 6, '4582529F-E9D8-45D1-BC0D-E180B7822D85')
Insert Into ProductCharacteristics VALUES( 17, '1EA9BFE9-8736-44DC-AFBB-E463CAB9FC5C')
Insert Into ProductCharacteristics VALUES( 4, '1EA9BFE9-8736-44DC-AFBB-E463CAB9FC5C')
Insert Into ProductCharacteristics VALUES( 5, '1EA9BFE9-8736-44DC-AFBB-E463CAB9FC5C')
Insert Into ProductCharacteristics VALUES( 2, '29ADB9BF-8D66-4E39-9C60-EE3E45A07E7A')
Insert Into ProductCharacteristics VALUES( 15, '29ADB9BF-8D66-4E39-9C60-EE3E45A07E7A')
Insert Into ProductCharacteristics VALUES( 12, '26A4A2E2-A60D-4234-83C4-F768B6C7764A')
Insert Into ProductCharacteristics VALUES( 18, '26A4A2E2-A60D-4234-83C4-F768B6C7764A')
Insert Into ProductCharacteristics VALUES( 9, '26A4A2E2-A60D-4234-83C4-F768B6C7764A')
Insert Into ProductCharacteristics VALUES( 2, '26A4A2E2-A60D-4234-83C4-F768B6C7764A')
Insert Into ProductCharacteristics VALUES( 1, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF')
Insert Into ProductCharacteristics VALUES( 5, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF')
Insert Into ProductCharacteristics VALUES( 17, 'F95DCF90-4C49-44BF-AACD-FF98ADBAE1CF')